# Generated by Django 2.2.11 on 2021-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permission', '0001_initial'),
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='associated_permissions',
            field=models.ManyToManyField(to='permission.HRSPermission'),
        ),
    ]
