# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_auto_20210211_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='exported_as',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Completed', 'Completed')], db_index=True, default='Queued', max_length=10),
        ),
    ]
