# Generated by Django 2.2.11 on 2022-04-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0004_auto_20210629_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='exported_as',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Supervisor', 'Supervisor')], db_index=True, max_length=10),
        ),
    ]
