# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0002_userassessment_associated_training'),
        ('questionnaire', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userassessment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_userassessment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_userassessment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userassessment',
            name='user',
            field=models.ForeignKey(help_text='The user that gave this assessment.', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='answers',
            field=models.ManyToManyField(help_text='All the choices user can make.', to='questionnaire.Answer'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questionresponse_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_questionresponse_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='assessment.AssessmentSection'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='user_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='assessment.UserAssessment'),
        ),
        migrations.AddField(
            model_name='assessmentset',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_assessmentset_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentset',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_assessmentset_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='assessment_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessment.AssessmentSet'),
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_assessmentsection_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_assessmentsection_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='questions',
            field=models.ManyToManyField(related_name='_assessmentsection_questions_+', through='assessment.AssessmentQuestions', to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='assessmentquestions',
            name='assessment_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_questions', to='assessment.AssessmentSection'),
        ),
        migrations.AddField(
            model_name='assessmentquestions',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_assessmentquestions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentquestions',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_assessmentquestions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentset',
            unique_together={('organization', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestions',
            unique_together={('assessment_section', 'question')},
        ),
    ]
