# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20210211_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('hold', 'Hold'), ('cancelled', 'Cancelled')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('hold', 'Hold'), ('cancelled', 'Cancelled')], db_index=True, help_text='Status of this assessment: Pending, In Progress, Completed, etc.', max_length=20),
        ),
    ]
