# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('payroll', '0001_initial'),
        ('organization', '0002_auto_20210211_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperiencepackageslot',
            name='user_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_experience_packages', to='users.UserExperience'),
        ),
        migrations.AddField(
            model_name='unitofworkrequesthistory',
            name='action_performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acted_unit_of_work', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitofworkrequesthistory',
            name='action_performed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_unit_of_work_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitofworkrequesthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_unitofworkrequesthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitofworkrequesthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_unitofworkrequesthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitofworkrequesthistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='payroll.UnitOfWorkRequest'),
        ),
        migrations.AddField(
            model_name='unitofworkrequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_unitofworkrequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitofworkrequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_unitofworkrequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitofworkrequest',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_work_requests', to='payroll.OperationRate'),
        ),
        migrations.AddField(
            model_name='unitofworkrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_unit_of_work_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitofworkrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_work_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signedpayrollhistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_signedpayrollhistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signedpayrollhistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_signedpayrollhistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signedpayrollhistory',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_payrolls', to='payroll.Payroll'),
        ),
        migrations.AddField(
            model_name='salaryholding',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportsalarybreakdownrangeconfig',
            name='overview_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_breakdown_ranges', to='payroll.OverviewConfig'),
        ),
        migrations.AddField(
            model_name='reportrowuserexperiencepackage',
            name='package_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_rows', to='payroll.PackageHeading'),
        ),
        migrations.AddField(
            model_name='reportrowuserexperiencepackage',
            name='package_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_rows', to='payroll.UserExperiencePackageSlot'),
        ),
        migrations.AddField(
            model_name='reportrowrecord',
            name='employee_payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_rows', to='payroll.EmployeePayroll'),
        ),
        migrations.AddField(
            model_name='reportrowrecord',
            name='package_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_rows', to='payroll.PackageHeading'),
        ),
        migrations.AddField(
            model_name='payrollincrement',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollincrement_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollincrement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_increments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollincrement',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollincrement_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollgenerationhistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollgenerationhistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollgenerationhistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollgenerationhistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollgenerationhistory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='payrollgenerationhistory',
            name='payroll',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation', to='payroll.Payroll'),
        ),
        migrations.AddField(
            model_name='payrolledithistoryamount',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payroll.PackageHeading'),
        ),
        migrations.AddField(
            model_name='payrolledithistoryamount',
            name='payroll_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_history', to='payroll.EmployeePayrollHistory'),
        ),
        migrations.AddField(
            model_name='payrollapprovalsetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollapprovalsetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollapprovalsetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollapprovalsetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollapprovalsetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_approval_settings', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='payrollapprovalsetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_approval_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollapprovalhistory',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_action_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollapprovalhistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollapprovalhistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollapprovalhistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollapprovalhistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollapprovalhistory',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_approval_histories', to='payroll.Payroll'),
        ),
        migrations.AddField(
            model_name='payrollapproval',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollapproval_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollapproval',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollapproval_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollapproval',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_approvals', to='payroll.Payroll'),
        ),
        migrations.AddField(
            model_name='payrollapproval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approval_pending',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payroll_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employees',
            field=models.ManyToManyField(related_name='payrolls', through='payroll.EmployeePayroll', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='packageheadingdependency',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_heading_dependencies', to='payroll.PackageHeading'),
        ),
        migrations.AddField(
            model_name='packageheadingdependency',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makes_package_heading_dependencies', to='payroll.PackageHeading'),
        ),
        migrations.AddField(
            model_name='packageheading',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='makes_dependency', through='payroll.PackageHeadingDependency', to='payroll.PackageHeading'),
        ),
        migrations.AddField(
            model_name='packageheading',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='packageheading',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_headings', to='payroll.Package'),
        ),
        migrations.AddField(
            model_name='package',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='actual_earned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actual_earned_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='cit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cit_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='cost_to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_to_company_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='gratuity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gratuity_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview_report_config', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='payroll_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_cost_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='provident_fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provident_fund_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='salary_payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_payable_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='salary_payment_detail_bar_graph_headings',
            field=models.ManyToManyField(blank=True, related_name='salary_payment_detail_bar_graph_headings_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='salary_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_range_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='overviewconfig',
            name='tds_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tds_payment_overview_configs', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='organizationpayrollconfig',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_payroll_config', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationpayrollconfig',
            name='start_fiscal_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_payroll_config', to='organization.FiscalYear'),
        ),
        migrations.AddField(
            model_name='operationrate',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_operationrate_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationrate',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_operationrate_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationrate',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='payroll.Operation'),
        ),
        migrations.AddField(
            model_name='operationrate',
            name='operation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='payroll.OperationCode'),
        ),
        migrations.AddField(
            model_name='operationcode',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_operationcode_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationcode',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_operationcode_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationcode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_codes', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='operation',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_operation_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operation',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_operation_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='headingdependency',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_dependencies', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='headingdependency',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makes_heading_dependencies', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='heading',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='makes_dependency', through='payroll.HeadingDependency', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='heading',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='externaltaxdiscount',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_externaltaxdiscount_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externaltaxdiscount',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_tax_discounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externaltaxdiscount',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_tax_discounts', to='organization.FiscalYear'),
        ),
        migrations.AddField(
            model_name='externaltaxdiscount',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_externaltaxdiscount_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayrollhistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_employeepayrollhistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayrollhistory',
            name='employee_payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payroll.EmployeePayroll'),
        ),
        migrations.AddField(
            model_name='employeepayrollhistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_employeepayrollhistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayrollhistory',
            name='packages',
            field=models.ManyToManyField(related_name='_employeepayrollhistory_packages_+', through='payroll.PayrollEditHistoryAmount', to='payroll.PackageHeading'),
        ),
        migrations.AddField(
            model_name='employeepayrollcomment',
            name='commented_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payroll_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayrollcomment',
            name='employee_payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payroll_comments', to='payroll.EmployeePayroll'),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_payrolls', to='payroll.Package'),
        ),
        migrations.AddField(
            model_name='employeepayroll',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_payrolls', to='payroll.Payroll'),
        ),
        migrations.AddField(
            model_name='approvalsetting',
            name='advance_salary_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_setting', to='payroll.AdvanceSalarySetting'),
        ),
        migrations.AddField(
            model_name='approvalsetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_approvalsetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalsetting',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalsetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_approvalsetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amountsetting',
            name='advance_salary_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_setting', to='payroll.AdvanceSalarySetting'),
        ),
        migrations.AddField(
            model_name='amountsetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_amountsetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amountsetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_amountsetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amountsetting',
            name='payroll_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_setting', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='advancesalarysurplusrequest',
            name='acted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_surplus_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalarysurplusrequest',
            name='advance_salary_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_request', to='payroll.AdvanceSalaryRequest'),
        ),
        migrations.AddField(
            model_name='advancesalarysurplusrequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalarysurplusrequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalarysurplusrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalarysurplusrequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalarysurplusrequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalarysetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalarysetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalarysetting',
            name='deduction_heading',
            field=models.ForeignKey(help_text='Heading used to deduct advance salary repayments.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='advancesalarysetting',
            name='excluded_employment_type',
            field=models.ManyToManyField(help_text='Exclude employees with certain employment types', to='organization.EmploymentStatus'),
        ),
        migrations.AddField(
            model_name='advancesalarysetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalarysetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalarysetting',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advance_salary_setting', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='advancesalaryrequesthistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrequesthistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='payroll.AdvanceSalaryRequest'),
        ),
        migrations.AddField(
            model_name='advancesalaryrequestdocument',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalaryrequestdocument_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrequestdocument',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalaryrequestdocument_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrequestdocument',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payroll.AdvanceSalaryRequest'),
        ),
        migrations.AddField(
            model_name='advancesalaryrequestapproval',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalaryrequestapproval_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrequestapproval',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalaryrequestapproval_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrequestapproval',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='payroll.AdvanceSalaryRequest'),
        ),
        migrations.AddField(
            model_name='advancesalaryrequestapproval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalaryrequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_salary_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalaryrequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_salary_requests_to_act', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrepayment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalaryrepayment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrepayment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_advancesalaryrepayment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advancesalaryrepayment',
            name='payroll_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.EmployeePayroll'),
        ),
        migrations.AddField(
            model_name='advancesalaryrepayment',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='payroll.AdvanceSalaryRequest'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlyheadingdetail',
            unique_together={('heading', 'fiscal_year')},
        ),
        migrations.AlterUniqueTogether(
            name='reportrowuserexperiencepackage',
            unique_together={('package_slot', 'package_heading')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollapprovalsetting',
            unique_together={('organization', 'user'), ('organization', 'approval_level')},
        ),
        migrations.AlterUniqueTogether(
            name='payrollapproval',
            unique_together={('user', 'payroll')},
        ),
        migrations.AlterUniqueTogether(
            name='packageheading',
            unique_together={('heading', 'package')},
        ),
        migrations.AlterUniqueTogether(
            name='operationrate',
            unique_together={('operation', 'operation_code')},
        ),
        migrations.AlterUniqueTogether(
            name='operationcode',
            unique_together={('title', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('title', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='heading',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='employeepayroll',
            unique_together={('employee', 'payroll')},
        ),
        migrations.AlterUniqueTogether(
            name='approvalsetting',
            unique_together={('advance_salary_setting', 'approval_level'), ('advance_salary_setting', 'employee'), ('advance_salary_setting', 'supervisor_level')},
        ),
        migrations.AlterUniqueTogether(
            name='amountsetting',
            unique_together={('advance_salary_setting', 'payroll_heading')},
        ),
    ]
