# Generated by Django 2.2.11 on 2021-03-19 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolledithistoryamount',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payroll.Heading'),
        ),
        migrations.AddField(
            model_name='reportrowrecord',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_rows', to='payroll.Heading'),
        ),
        migrations.AlterField(
            model_name='employeepayrollhistory',
            name='packages',
            field=models.ManyToManyField(related_name='_employeepayrollhistory_packages_+', through='payroll.PayrollEditHistoryAmount', to='payroll.Heading'),
        ),
        migrations.AlterField(
            model_name='payrolledithistoryamount',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payroll.PackageHeading'),
        ),
        migrations.AlterField(
            model_name='reportrowrecord',
            name='package_heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_rows', to='payroll.PackageHeading'),
        ),
    ]
