# Generated by Django 2.2.11 on 2021-03-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210211_1614'),
        ('payroll', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSFReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headings', models.ManyToManyField(related_name='ssf_report', to='payroll.Heading')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
    ]
