# Generated by Django 2.2.11 on 2021-03-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20210319_1820'),
        ('payroll', '0003_ssfreportsetting'),
    ]

    operations = [
    ]
