# Generated by Django 2.2.11 on 2021-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_merge_20210330_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperiencepackageslot',
            name='backdated_calculation_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userexperiencepackageslot',
            name='backdated_calculation_generated',
            field=models.BooleanField(default=False),
        ),
    ]
