# Generated by Django 2.2.11 on 2021-04-22 10:59

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_auto_20210211_1614'),
        ('payroll', '0005_disbursementreportsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='MonthlyTaxReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Employment Income', 'Employment Income'), ('Less: Allowable Deduction', 'Less: Allowable Deduction'), ('Less: Allowable Reduction', 'Less: Allowable Reduction'), ('Tax Calculation', 'Tax Calculation')], max_length=200)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_monthlytaxreportsetting_created', to=settings.AUTH_USER_MODEL)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_employee_tax_report_setting_particulars', to='payroll.Heading')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_monthlytaxreportsetting_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_employee_tax_report_settings', to='organization.Organization')),
            ],
        ),
        migrations.AddConstraint(
            model_name='monthlytaxreportsetting',
            constraint=models.UniqueConstraint(fields=('organization', 'category', 'heading'), name='unique_organization_category_heading'),
        ),
    ]
