# Generated by Django 2.2.11 on 2021-03-22 12:31

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0005_auto_20210322_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackdatedCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('previous_amount', models.FloatField(blank=True, null=True)),
                ('current_amount', models.FloatField(blank=True, null=True)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_backdatedcalculation_created', to=settings.AUTH_USER_MODEL)),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backdated_calculations', to='payroll.Heading')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_backdatedcalculation_modified', to=settings.AUTH_USER_MODEL)),
                ('package_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backdated_calculations', to='payroll.UserExperiencePackageSlot')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
