# Generated by Django 2.2.11 on 2021-04-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_backdatedcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='backdatedcalculation',
            name='adjusted_payroll',
            field=models.ForeignKey(help_text='Employee Payroll Instance where this record is adjusted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.EmployeePayroll'),
        ),
    ]
