# Generated by Django 2.2.11 on 2021-04-07 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_disbursementreportsetting'),
        ('payroll', '0006_backdatedcalculation'),
    ]

    operations = [
    ]
