# Generated by Django 2.2.11 on 2021-04-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20210422_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytaxreportsetting',
            name='is_nested',
            field=models.BooleanField(default=False),
        ),
    ]
