# Generated by Django 2.2.11 on 2021-04-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_merge_20210407_0832'),
        ('payroll', '0007_backdatedcalculation_adjusted_payroll'),
    ]

    operations = [
    ]
