# Generated by Django 2.2.11 on 2021-04-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_monthlytaxreportsetting_is_nested'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrowrecord',
            name='projected_amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
