# Generated by Django 2.2.11 on 2021-04-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_merge_20210408_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backdatedcalculation',
            options={'ordering': ('heading__order', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='reportrowrecord',
            options={'ordering': ('heading__order',)},
        ),
        migrations.AlterField(
            model_name='backdatedcalculation',
            name='adjusted_payroll',
            field=models.ForeignKey(help_text='Employee Payroll Instance where this record is adjusted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_backdated_calculations', to='payroll.EmployeePayroll'),
        ),
    ]
