# Generated by Django 2.2.11 on 2021-04-30 17:02

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irhrs.payroll.models.plugin


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_auto_20210211_1614'),
        ('payroll', '0009_auto_20210415_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollVariablePlugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, validators=[irhrs.payroll.models.plugin.validate_plugin_name])),
                ('checksum', models.TextField()),
                ('signature', models.TextField()),
                ('module', models.BinaryField(editable=True)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollvariableplugin_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollvariableplugin_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_variable_plugins', to='organization.Organization')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
