# Generated by Django 2.2.11 on 2021-05-03 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20210415_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewconfig',
            name='cash_in_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_in_hand_overview_configs', to='payroll.Heading'),
        ),
    ]
