# Generated by Django 2.2.11 on 2021-04-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_reportrowrecord_projected_amount'),
        ('payroll', '0009_auto_20210415_1141'),
    ]

    operations = [
    ]
