# Generated by Django 2.2.11 on 2021-05-03 04:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import irhrs.payroll.models.plugin


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210211_1614'),
        ('payroll', '0010_payrollvariableplugin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollvariableplugin',
            options={},
        ),
        migrations.AddField(
            model_name='payrollvariableplugin',
            name='module_props',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payrollvariableplugin',
            name='name',
            field=models.CharField(blank=True, max_length=200, validators=[irhrs.payroll.models.plugin.validate_plugin_name]),
        ),
        migrations.AlterUniqueTogether(
            name='payrollvariableplugin',
            unique_together={('name', 'organization')},
        ),
        migrations.RemoveField(
            model_name='payrollvariableplugin',
            name='checksum',
        ),
    ]
