# Generated by Django 2.2.11 on 2021-04-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_merge_20210426_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportrowrecord',
            name='projected_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
