# Generated by Django 2.2.11 on 2021-05-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20210503_1001'),
        ('payroll', '0011_auto_20210426_2306'),
    ]

    operations = [
    ]
