# Generated by Django 2.2.11 on 2021-05-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_reportrowrecord_plugin_sources'),
        ('payroll', '0010_overviewconfig_cash_in_hand'),
    ]

    operations = [
    ]
