# Generated by Django 2.2.11 on 2021-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_merge_20210506_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytaxreportsetting',
            name='category',
            field=models.CharField(choices=[('Employment Income', 'Employment Income'), ('Less: Allowable Deductions', 'Less: Allowable Deductions'), ('Less: Allowable Reductions', 'Less: Allowable Reductions'), ('Tax Calculation', 'Tax Calculation')], max_length=200),
        ),
    ]
