# Generated by Django 2.2.11 on 2021-05-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_auto_20210506_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='is_editable',
            field=models.BooleanField(default=True),
        ),
    ]
