# Generated by Django 2.2.11 on 2021-05-08 16:05

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irhrs.core.utils.common


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0015_auto_20210506_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollExcelUpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('excel_file', models.FileField(upload_to=irhrs.core.utils.common.get_upload_path)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Done', 'Done'), ('Failed', 'Failed')], max_length=150)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollexcelupdatehistory_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payrollexcelupdatehistory_modified', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_updates', to='payroll.Payroll')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
