# Generated by Django 2.2.11 on 2021-05-10 04:44

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0015_auto_20210506_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationrate',
            name='unit',
            field=models.CharField(choices=[('hour', 'hour'), ('piece', 'piece')], default='hour', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserOperationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_useroperationrate_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_useroperationrate_modified', to=settings.AUTH_USER_MODEL)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_operation_rate', to='payroll.OperationRate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_operation_rate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rate')},
            },
        ),
    ]
