# Generated by Django 2.2.11 on 2021-05-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_heading_is_editable'),
        ('payroll', '0016_payrollexcelupdatehistory'),
    ]

    operations = [
    ]
