# Generated by Django 2.2.11 on 2021-05-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_auto_20210510_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofworkrequest',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
