# Generated by Django 2.2.11 on 2021-05-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_merge_20210513_1511'),
        ('payroll', '0017_auto_20210514_1632'),
    ]

    operations = [
    ]
