# Generated by Django 2.2.11 on 2021-05-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_merge_20210518_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='visible_in_package_basic_view',
            field=models.BooleanField(default=False),
        ),
    ]
