# Generated by Django 2.2.11 on 2021-05-21 06:21

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20210510_1748'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0018_merge_20210518_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoluntaryRebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Health Insurance', 'Health Insurance'), ('Other Insurance', 'Other Insurance'), ('Donation', 'Donation'), ('CIT', 'CIT')], max_length=120)),
                ('duration_unit', models.CharField(choices=[('Health Insurance', 'Health Insurance'), ('Other Insurance', 'Other Insurance'), ('Donation', 'Donation'), ('CIT', 'CIT')], max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_uservoluntaryrebate_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntary_rebates', to='organization.FiscalYear')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_uservoluntaryrebate_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voluntary_rebates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserVoluntaryRebateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_uservoluntaryrebatedocument_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_uservoluntaryrebatedocument_modified', to=settings.AUTH_USER_MODEL)),
                ('user_voluntary_rebate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payroll.UserVoluntaryRebate')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserVoluntaryRebateAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('Create Request', 'Create Request'), ('Created', 'Created'), ('Create Rejected', 'Create Rejected'), ('Delele Request', 'Delele Request'), ('Deleted', 'Deleted'), ('Delete Rejected', 'Delete Rejected')], max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_uservoluntaryrebateaction_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_uservoluntaryrebateaction_modified', to=settings.AUTH_USER_MODEL)),
                ('user_voluntary_rebate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='payroll.UserVoluntaryRebate')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
