# Generated by Django 2.2.11 on 2021-05-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_auto_20210521_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoluntaryrebateaction',
            name='action',
            field=models.CharField(choices=[('Create Request', 'Create Request'), ('Created', 'Created'), ('Create Rejected', 'Create Rejected'), ('Delete Request', 'Delete Request'), ('Deleted', 'Deleted'), ('Delete Rejected', 'Delete Rejected')], max_length=20),
        ),
    ]
