# Generated by Django 2.2.11 on 2021-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_auto_20210524_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoluntaryrebateaction',
            name='action',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Archive Requested', 'Archive Requested'), ('Archived', 'Archived'), ('Archive Denied', 'Archive Denied')], max_length=20),
        ),
    ]
