# Generated by Django 2.2.11 on 2021-05-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_heading_visible_in_package_basic_view'),
        ('payroll', '0023_auto_20210524_1837'),
    ]

    operations = [
    ]
