# Generated by Django 2.2.11 on 2021-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_auto_20210524_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoluntaryrebate',
            name='description',
            field=models.CharField(default='Default description', max_length=200),
            preserve_default=False,
        ),
    ]
