# Generated by Django 2.2.11 on 2021-05-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_auto_20210525_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoluntaryrebate',
            name='type',
            field=models.CharField(choices=[('Health Insurance', 'Health Insurance'), ('Life Insurance', 'Life Insurance'), ('Other Insurance', 'Other Insurance'), ('Donation', 'Donation'), ('CIT', 'CIT')], max_length=120),
        ),
    ]
