# Generated by Django 2.2.11 on 2021-05-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_auto_20210525_1636'),
        ('payroll', '0019_heading_visible_in_package_basic_view'),
    ]

    operations = [
    ]
