# Generated by Django 2.2.11 on 2021-05-27 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_merge_20210525_1325'),
        ('payroll', '0026_auto_20210525_1636'),
    ]

    operations = [
    ]
