# Generated by Django 2.2.11 on 2021-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_merge_20210527_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoluntaryrebate',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uservoluntaryrebate',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='uservoluntaryrebate',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uservoluntaryrebateaction',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
