# Generated by Django 2.2.11 on 2021-06-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_auto_20210527_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoluntaryrebatedocument',
            name='file_name',
            field=models.CharField(default='default_filename.pdf', max_length=150),
            preserve_default=False,
        ),
    ]
