# Generated by Django 2.2.11 on 2021-06-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_uservoluntaryrebatedocument_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoluntaryrebateaction',
            name='remarks',
            field=models.CharField(max_length=255),
        ),
    ]
