# Generated by Django 2.2.11 on 2021-07-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_auto_20210609_1331'),
        ('payroll', '0027_merge_20210527_0921'),
    ]

    operations = [
    ]
