# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_auto_20210609_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalaryrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Repayment', 'Repayment'), ('Denied', 'Denied'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], db_index=True, default='Requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='advancesalaryrequestapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='advancesalarysurplusrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied')], db_index=True, default='Requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='acknowledgement_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged')], db_index=True, default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Approval Pending', 'Approval Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Confirmed', 'Confirmed')], db_index=True, default='Generated', max_length=50),
        ),
        migrations.AlterField(
            model_name='payrollapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='payrollexcelupdatehistory',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Done', 'Done'), ('Failed', 'Failed')], db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='payrollgenerationhistory',
            name='status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Completed', 'Completed')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='unitofworkrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled'), ('Confirmed', 'Confirmed')], db_index=True, default='Requested', max_length=25),
        ),
    ]
