# Generated by Django 2.2.11 on 2021-07-01 09:52

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_auto_20210629_1553'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeepayroll',
            index=models.Index(fields=['employee', 'payroll', 'package'], name='payroll_emp_employe_2d05cf_idx'),
        ),
        migrations.AddIndex(
            model_name='heading',
            index=models.Index(fields=['order', 'organization'], name='payroll_hea_order_c4da80_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['organization', 'from_date', 'to_date'], name='payroll_pay_organiz_ec9602_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=django.contrib.postgres.indexes.HashIndex(fields=['status'], name='payroll_pay_status_26bad5_hash'),
        ),
        migrations.AddIndex(
            model_name='reportrowrecord',
            index=models.Index(fields=['employee_payroll', '-from_date', '-to_date'], name='report_row_composite_index'),
        ),
        migrations.AddIndex(
            model_name='reportrowuserexperiencepackage',
            index=models.Index(fields=['-package_slot', 'package_heading'], name='payroll_rep_package_a6397d_idx'),
        ),
        migrations.AddIndex(
            model_name='userexperiencepackageslot',
            index=models.Index(fields=['user_experience', 'package', '-active_from_date'], name='payroll_use_user_ex_4e3c83_idx'),
        ),
    ]
