# Generated by Django 2.2.11 on 2021-07-28 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20210629_1553'),
        ('payroll', '0032_auto_20210701_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headings', models.ManyToManyField(related_name='tax_report', to='payroll.Heading')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
    ]
