# Generated by Django 2.2.11 on 2021-07-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_auto_20210701_1537'),
        ('payroll', '0031_merge_20210714_1637'),
    ]

    operations = [
    ]
