# Generated by Django 2.2.11 on 2021-08-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_merge_20210716_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoluntaryrebate',
            name='type',
            field=models.CharField(choices=[('Health Insurance', 'Health Insurance'), ('Life Insurance', 'Life Insurance'), ('Donation', 'Donation'), ('CIT', 'CIT')], max_length=120),
        ),
    ]
