# Generated by Django 2.2.11 on 2021-08-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_taxreportsetting'),
        ('payroll', '0034_auto_20210804_1652'),
    ]

    operations = [
    ]
