# Generated by Django 2.2.11 on 2022-04-20 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_auto_20220323_1516'),
        ('payroll', '0035_merge_20210805_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollCollectionDetailReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headings', models.ManyToManyField(related_name='_payrollcollectiondetailreportsetting_headings_+', to='payroll.Heading')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
