# Generated by Django 3.2.12 on 2022-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_merge_20210805_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='absent_days_impact',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='deduct_amount_on_leave',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='pay_when_present_holiday_offday',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='taxable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageheading',
            name='absent_days_impact',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageheading',
            name='deduct_amount_on_leave',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='packageheading',
            name='pay_when_present_holiday_offday',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='packageheading',
            name='taxable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
