# Generated by Django 3.2.12 on 2022-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_auto_20220307_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalaryrequest',
            name='repayment_plan',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='rules',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='packageheading',
            name='rules',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='extra_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='payrollgenerationhistory',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='payrollgenerationhistory',
            name='errors',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='reportrowrecord',
            name='plugin_sources',
            field=models.JSONField(default=list),
        ),
    ]
