# Generated by Django 2.2.11 on 2022-04-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_payrollcollectiondetailreportsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disbursementreportsetting',
            name='headings',
            field=models.ManyToManyField(related_name='_disbursementreportsetting_headings_+', to='payroll.Heading'),
        ),
        migrations.AlterField(
            model_name='ssfreportsetting',
            name='headings',
            field=models.ManyToManyField(related_name='_ssfreportsetting_headings_+', to='payroll.Heading'),
        ),
        migrations.AlterField(
            model_name='taxreportsetting',
            name='headings',
            field=models.ManyToManyField(related_name='_taxreportsetting_headings_+', to='payroll.Heading'),
        ),
    ]
