# Generated by Django 3.2.12 on 2022-03-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0037_auto_20220307_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollvariableplugin',
            name='module_props',
            field=models.JSONField(),
        ),
    ]
