# Generated by Django 2.2.11 on 2022-04-22 10:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_auto_20220323_1516'),
        ('payroll', '0037_auto_20220421_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraHeadingReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Designation', 'Designation'), ('Employment Level', 'Employment Level'), ('Employment Type', 'Employment Type'), ('Branch', 'Branch'), ('Step', 'Step'), ('Package Name', 'Package Name'), ('Working Days', 'Working Days'), ('Worked Days', 'Worked Days'), ('Absent Days', 'Absent Days'), ('Worked Hours', 'Worked Hours'), ('Overtime Hours', 'Overtime Hours'), ('SSF Number', 'SSF Number'), ('Bank Name', 'Bank Name'), ('Bank Branch', 'Bank Branch'), ('Bank Account Number', 'Bank Account Number'), ('PF Number', 'PF Number'), ('PAN Number', 'PAN Number'), ('CIT Number', 'CIT Number')], max_length=30), size=None)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
        ),
    ]
