# Generated by Django 3.2.12 on 2022-05-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0038_alter_payrollvariableplugin_module_props'),
        ('payroll', '0038_extraheadingreportsetting'),
    ]

    operations = [
    ]
