# Generated by Django 2.2.11 on 2022-06-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0038_extraheadingreportsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpayrollconfig',
            name='show_generated_payslip',
            field=models.BooleanField(default=False, help_text='Show payslip to users once generated if true.else, payslip is only shown when confirmed.'),
        ),
        migrations.AlterField(
            model_name='employeepayroll',
            name='acknowledgement_status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Pending', 'Pending'), ('Acknowledged', 'Acknowledged')], db_index=True, default='Generated', max_length=30),
        ),
    ]
