# Generated by Django 2.2.11 on 2022-07-21 06:53

from django.db import migrations, models
import django.db.models.deletion
import irhrs.payroll.utils.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_auto_20220419_1125'),
        ('payroll', '0039_auto_20220607_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebateSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=30)),
                ('duration_type', models.CharField(choices=[('Yearly', 'Yearly'), ('Monthly', 'Monthly')], max_length=20)),
                ('amount', models.FloatField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebate_settings', to='organization.Organization')),
            ],
            options={
                'unique_together': {('title', 'duration_type', 'organization')},
            },
            bases=(irhrs.payroll.utils.mixins.VueRouteMixin, models.Model),
        ),
    ]
