# Generated by Django 3.2.12 on 2022-06-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0039_auto_20220607_0928'),
        ('payroll', '0039_merge_20220516_1100'),
    ]

    operations = [
    ]
