# Generated by Django 3.2.12 on 2022-07-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0040_merge_20220613_0923'),
        ('payroll', '0041_auto_20220727_1542'),
    ]

    operations = [
    ]
