# Generated by Django 3.2.12 on 2022-09-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_auto_20220819_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpayrollconfig',
            name='display_heading_with_zero_value',
            field=models.BooleanField(default=False, help_text='disly headings with zero values if true'),
        ),
    ]
