# Generated by Django 3.2.12 on 2022-09-29 03:17

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_merge_20220516_1058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0044_organizationpayrollconfig_display_heading_with_zero_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelPayrollPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Processing', max_length=10)),
                ('cloned_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.package')),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_excelpayrollpackage_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_excelpayrollpackage_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='package',
            name='excel_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='payroll.excelpayrollpackage'),
        ),
        migrations.AddField(
            model_name='userexperiencepackageslot',
            name='excel_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_slots', to='payroll.excelpayrollpackage'),
        ),
    ]
