# Generated by Django 3.2.12 on 2022-11-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0047_alter_payroll_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalaryrequesthistory',
            name='target',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
