# Generated by Django 3.2.12 on 2023-03-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0048_alter_advancesalaryrequesthistory_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='deduct_amount_on_remote_work',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='packageheading',
            name='deduct_amount_on_remote_work',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
