# Generated by Django 3.2.12 on 2023-04-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0049_alter_extraheadingreportsetting_headings'),
        ('payroll', '0049_auto_20230329_1705'),
    ]

    operations = [
    ]
