# Generated by Django 3.2.12 on 2023-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0052_alter_extraheadingreportsetting_headings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='hourly_heading_source',
            field=models.CharField(blank=True, choices=[('Overtime', 'Overtime'), ('Total Hour Worked', 'Total Hour Worked')], help_text='Choose Hourly Record', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='packageheading',
            name='hourly_heading_source',
            field=models.CharField(choices=[('Overtime', 'Overtime'), ('Total Hour Worked', 'Total Hour Worked')], help_text='Choose Hourly Record', max_length=25, null=True),
        ),
    ]
