# Generated by Django 3.2.12 on 2023-07-24 12:10

from django.db import migrations, models
from django.db.models import Value, F
from django.db.models.functions import Concat
from irhrs.payroll.models import Payroll


def set_default_payroll_title(apps, schema_editor):
    Payroll.objects.update(
        title=Concat(Value("From "), F('from_date'), Value(' To '), F('to_date')))


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0053_auto_20230523_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RunPython(set_default_payroll_title)
    ]
