# Generated by Django 3.2.12 on 2024-01-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_alter_emailnotificationsetting_email_type'),
        ('payroll', '0055_payrollemployeeaddedhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDifferenceDetailReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headings', models.ManyToManyField(related_name='_payroll_payrolldifferencedetailreportsetting_headings_+', to='payroll.Heading')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
