# Generated by Django 3.2.12 on 2024-01-17 05:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_alter_emailnotificationsetting_email_type'),
        ('payroll', '0056_payrolldifferencedetailreportsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMetricHeadingReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('working_days', 'working_days'), ('total_days', 'total_days'), ('worked_days', 'worked_days'), ('offday_count', 'offday_count'), ('absent_days', 'absent_days'), ('leave_days', 'leave_days'), ('leave_days_on_workdays', 'leave_days_on_workdays'), ('unpaid_leave_days', 'unpaid_leave_days'), ('paid_days', 'paid_days'), ('days_deduction_from_penalty', 'days_deduction_from_penalty'), ('holiday_count', 'holiday_count'), ('leave_paid_days', 'leave_paid_days'), ('worked_on_offday_holiday', 'worked_on_offday_holiday'), ('worked_hour', 'worked_hour'), ('total_claimed', 'total_claimed')], max_length=30), size=None)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
    ]
