name: Build Docker Image

on: 
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: itsbijaya/real-hr-frontend
            tags: latest
            registry: docker.io
            dockerfile: ./docker/Dockerfile.fe
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}    


  
        
