version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

  backend:
    image: itsbijaya/real-hr-backend:latest
    container_name: real-hr-backend
    env_file:
      - .env
    ports:
      - "8080:8080"  
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - my_network

volumes:
  postgres_data:
  redis_data:
networks: 
  my_network:
      driver: bridge
        
