# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
        ('organization', '0002_auto_20210211_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_questioncategory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_questioncategory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(help_text='Question Category. Eg: Easy, Medium, Hard, etc.', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questionnaire.QuestionCategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_question_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_question_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='answer',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_answer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_answer_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_answer_choices', to='questionnaire.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='questioncategory',
            unique_together={('title', 'organization', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'title')},
        ),
    ]
