# Generated by Django 2.2.11 on 2021-02-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weightage',
            field=models.PositiveIntegerField(help_text='The weightage of the question. Or, can be called `marks`', null=True),
        ),
    ]
