# Generated by Django 2.2.11 on 2021-02-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20210215_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='weightage',
            field=models.PositiveIntegerField(blank=True, help_text='The weightage of the question. Or, can be called `marks`', null=True),
        ),
    ]
