# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20210218_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_choices',
            field=models.CharField(choices=[('multiple-mcq', 'Checkbox'), ('single-mcq', 'Radio Button'), ('linear-scale', 'Linear Scale'), ('short-text', 'Short Answer'), ('long-text', 'Long Answer'), ('rating-scale', 'Rating Scale')], db_index=True, help_text='The types of answer choices. Eg: MCQ, Linear Scale, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('assessment', 'Assessment'), ('performance_appraisal', 'Performance Appraisal'), ('interview_evaluation', 'Interview'), ('feedback', 'Feedback'), ('vacancy', 'Vacancy Question'), ('reference_check', 'Reference Check'), ('exit_interview', 'Exit Interview'), ('pre_screening', 'Pre Screening'), ('post_screening', 'Post Screening'), ('pre_screening_interview', 'Pre Screening Interview')], db_index=True, help_text='Question Type. Eg: Assessment, PA, Feedback, Interview, etc.', max_length=25),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='category',
            field=models.CharField(choices=[('assessment', 'Assessment'), ('performance_appraisal', 'Performance Appraisal'), ('interview_evaluation', 'Interview'), ('feedback', 'Feedback'), ('vacancy', 'Vacancy Question'), ('reference_check', 'Reference Check'), ('exit_interview', 'Exit Interview'), ('pre_screening', 'Pre Screening'), ('post_screening', 'Post Screening'), ('pre_screening_interview', 'Pre Screening Interview')], db_index=True, max_length=25),
        ),
    ]
