# Generated by Django 2.2.11 on 2021-07-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20210726_0853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'title', 'attachment')},
        ),
    ]
