# Generated by Django 2.2.11 on 2021-09-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20210728_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
