# Generated by Django 2.2.11 on 2021-10-19 09:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20211018_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
