# Generated by Django 3.2.12 on 2022-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_question_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='extra_data',
            field=models.JSONField(null=True),
        ),
    ]
