# Generated by Django 3.2.12 on 2023-01-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_alter_question_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(help_text='Question Text.', max_length=1000),
        ),
    ]
