# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('help', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helpquestionfeedback',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_helpquestionfeedback_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpquestionfeedback',
            name='help_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='help.HelpQuestion'),
        ),
        migrations.AddField(
            model_name='helpquestionfeedback',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_helpquestionfeedback_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpquestionfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpquestion',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_helpquestion_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpquestion',
            name='help_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='help.HelpCategory'),
        ),
        migrations.AddField(
            model_name='helpquestion',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_helpquestion_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='help.HelpQuestion'),
        ),
        migrations.AddField(
            model_name='helpmodule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_helpmodule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpmodule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_helpmodule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_helpcategory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='help_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='help.HelpModule'),
        ),
        migrations.AddField(
            model_name='helpcategory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_helpcategory_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
