# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrstatement', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hrpolicyheading',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrstatement_hrpolicyheading_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrpolicyheading',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrstatement_hrpolicyheading_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrpolicyheading',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='hrpolicybody',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrstatement_hrpolicybody_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrpolicybody',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_bodies', to='hrstatement.HRPolicyHeading'),
        ),
        migrations.AddField(
            model_name='hrpolicybody',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrstatement_hrpolicybody_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrpolicybody',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_bodies', to='hrstatement.HRPolicyBody'),
        ),
        migrations.AlterUniqueTogether(
            name='hrpolicyheading',
            unique_together={('order_field', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='hrpolicybody',
            unique_together={('title', 'order_field')},
        ),
    ]
