# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrstatement', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrpolicyheading',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished')], db_index=True, default='Unpublished', max_length=50),
        ),
    ]
