# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
        ('organization', '0001_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktiming',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_worktiming_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worktiming',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_worktiming_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worktiming',
            name='work_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='attendance.WorkDay'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_workshift_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshift',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_workshift_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshift',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='workday',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_workday_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workday',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_workday_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workday',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='attendance.WorkShift'),
        ),
        migrations.AddField(
            model_name='webattendancefilter',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_filters', to='attendance.IndividualAttendanceSetting'),
        ),
        migrations.AddField(
            model_name='travelattendancesetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancesetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancesetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancesetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancesetting',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_setting', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='travelattendancerequesthistory',
            name='action_performed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancerequesthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancerequesthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancerequesthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancerequesthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancerequesthistory',
            name='travel_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='attendance.TravelAttendanceRequest'),
        ),
        migrations.AddField(
            model_name='travelattendancerequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancerequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancerequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancerequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancerequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_attendance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancedeleterequesthistory',
            name='action_performed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancedeleterequesthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancedeleterequesthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancedeleterequesthistory',
            name='delete_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='attendance.TravelAttendanceDeleteRequest'),
        ),
        migrations.AddField(
            model_name='travelattendancedeleterequesthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancedeleterequesthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancedeleterequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancedeleterequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancedeleterequest',
            name='deleted_days',
            field=models.ManyToManyField(to='attendance.TravelAttendanceDays'),
        ),
        migrations.AddField(
            model_name='travelattendancedeleterequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancedeleterequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancedeleterequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancedeleterequest',
            name='travel_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_request', to='attendance.TravelAttendanceRequest'),
        ),
        migrations.AddField(
            model_name='travelattendancedays',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancedays_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancedays',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_travelattendancedays_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendancedays',
            name='timesheets',
            field=models.ManyToManyField(to='attendance.TimeSheet'),
        ),
        migrations.AddField(
            model_name='travelattendancedays',
            name='travel_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_attendances', to='attendance.TravelAttendanceRequest'),
        ),
        migrations.AddField(
            model_name='travelattendancedays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_attendance_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelattendanceattachments',
            name='travel_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='attendance.TravelAttendanceRequest'),
        ),
        migrations.AddField(
            model_name='timesheetreportrequesthistory',
            name='action_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_to_timesheet_report_request_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetreportrequesthistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_timesheet_report_request_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetreportrequesthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetreportrequesthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetreportrequesthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetreportrequesthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetreportrequesthistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='attendance.TimeSheetReportRequest'),
        ),
        migrations.AddField(
            model_name='timesheetreportrequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetreportrequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetreportrequest',
            name='fiscal_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.FiscalYearMonth'),
        ),
        migrations.AddField(
            model_name='timesheetreportrequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetreportrequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetreportrequest',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_report_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetreportrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetregistrationreportsettings',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetregistrationreportsettings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetregistrationreportsettings',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetregistrationreportsettings_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetregistrationreportsettings',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_registration_report_setting', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='timesheetregistrationreportsettings',
            name='selected_leave_types',
            field=models.ManyToManyField(related_name='selected_timesheet_registration_report_setting', to='leave.LeaveType'),
        ),
        migrations.AddField(
            model_name='timesheetentryapproval',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetentryapproval_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetentryapproval',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetentryapproval_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetentryapproval',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_entry_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetentryapproval',
            name='timesheet_approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entry_approval', to='attendance.TimeSheetApproval'),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetentry_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetentry_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='attendance.TimeSheet'),
        ),
        migrations.AddField(
            model_name='timesheetapproval',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetapproval_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetapproval',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheetapproval_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetapproval',
            name='timesheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_approval', to='attendance.TimeSheet'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheet_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='manual_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_timesheet_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='timesheet_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='work_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='attendance.WorkShift'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='work_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.WorkTiming'),
        ),
        migrations.AddField(
            model_name='preapprovalovertimehistory',
            name='action_performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preapprovalovertimehistory',
            name='action_performed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preapprovalovertimehistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_preapprovalovertimehistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preapprovalovertimehistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_preapprovalovertimehistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preapprovalovertimehistory',
            name='pre_approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='attendance.PreApprovalOvertime'),
        ),
        migrations.AddField(
            model_name='preapprovalovertime',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_preapprovalovertime_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preapprovalovertime',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_preapprovalovertime_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preapprovalovertime',
            name='overtime_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_approval', to='attendance.OvertimeEntry'),
        ),
        migrations.AddField(
            model_name='preapprovalovertime',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preapprovalovertime',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimesetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimesetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimesetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimesetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimesetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_settings', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='overtimerate',
            name='overtime_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='attendance.OvertimeSetting'),
        ),
        migrations.AddField(
            model_name='overtimeentrydetailhistory',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_adjustments_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeentrydetailhistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeentrydetailhistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeentrydetailhistory',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='attendance.OvertimeEntryDetail'),
        ),
        migrations.AddField(
            model_name='overtimeentrydetailhistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeentrydetailhistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeentrydetail',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeentrydetail_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeentrydetail',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeentrydetail_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeentrydetail',
            name='overtime_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_detail', to='attendance.OvertimeEntry'),
        ),
        migrations.AddField(
            model_name='overtimeentry',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeentry_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeentry',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeentry_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeentry',
            name='overtime_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.OvertimeSetting'),
        ),
        migrations.AddField(
            model_name='overtimeentry',
            name='timesheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='attendance.TimeSheet'),
        ),
        migrations.AddField(
            model_name='overtimeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeclaimhistory',
            name='action_performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_overtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeclaimhistory',
            name='action_performed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_overtimes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeclaimhistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeclaimhistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeclaimhistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeclaimhistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeclaimhistory',
            name='overtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_histories', to='attendance.OvertimeClaim'),
        ),
        migrations.AddField(
            model_name='overtimeclaim',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeclaim_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeclaim',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overtimeclaim_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtimeclaim',
            name='overtime_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='attendance.OvertimeEntry'),
        ),
        migrations.AddField(
            model_name='overtimeclaim',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualworkinghour',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_individualworkinghour_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualworkinghour',
            name='individual_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_setting_working_hours', to='attendance.IndividualAttendanceSetting'),
        ),
        migrations.AddField(
            model_name='individualworkinghour',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_individualworkinghour_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualusershift',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_individualusershift_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualusershift',
            name='individual_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_setting_shift', to='attendance.IndividualAttendanceSetting'),
        ),
        migrations.AddField(
            model_name='individualusershift',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_individualusershift_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualusershift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_shifts', to='attendance.WorkShift'),
        ),
        migrations.AddField(
            model_name='individualattendancesetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_individualattendancesetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualattendancesetting',
            name='credit_hour_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_settings', to='attendance.CreditHourSetting'),
        ),
        migrations.AddField(
            model_name='individualattendancesetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_individualattendancesetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualattendancesetting',
            name='overtime_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_settings', to='attendance.OvertimeSetting'),
        ),
        migrations.AddField(
            model_name='individualattendancesetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourtimesheetentry',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourtimesheetentry_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourtimesheetentry',
            name='credit_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='attendance.CreditHourSetting'),
        ),
        migrations.AddField(
            model_name='credithourtimesheetentry',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourtimesheetentry_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourtimesheetentry',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to='attendance.TimeSheet'),
        ),
        migrations.AddField(
            model_name='credithoursetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithoursetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithoursetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithoursetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithoursetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_hour_settings', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='credithoursetting',
            name='overtime_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.OvertimeSetting'),
        ),
        migrations.AddField(
            model_name='credithourrequesthistory',
            name='action_performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrequesthistory',
            name='action_performed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrequesthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourrequesthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrequesthistory',
            name='credit_hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='attendance.CreditHourRequest'),
        ),
        migrations.AddField(
            model_name='credithourrequesthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourrequesthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourrequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrequest',
            name='credit_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_request', to='attendance.CreditHourTimeSheetEntry'),
        ),
        migrations.AddField(
            model_name='credithourrequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourrequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrequest',
            name='travel_attendance_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_hour_requests', to='attendance.TravelAttendanceRequest'),
        ),
        migrations.AddField(
            model_name='credithourdeleterequesthistory',
            name='action_performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourdeleterequesthistory',
            name='action_performed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourdeleterequesthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourdeleterequesthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourdeleterequesthistory',
            name='delete_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='attendance.CreditHourDeleteRequest'),
        ),
        migrations.AddField(
            model_name='credithourdeleterequesthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourdeleterequesthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourdeleterequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourdeleterequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourdeleterequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_credithourdeleterequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourdeleterequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourdeleterequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to='attendance.CreditHourRequest'),
        ),
        migrations.AddField(
            model_name='credithourdeleterequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakoutuserrecordstatushistory',
            name='break_out_user_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='attendance.BreakOutUserRecord'),
        ),
        migrations.AddField(
            model_name='breakoutuserrecordstatushistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breakoutuserrecordstatushistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakoutuserrecordstatushistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breakoutuserrecordstatushistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakoutuserrecord',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breakoutuserrecord_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakoutuserrecord',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breakoutuserrecord_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakoutuserrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_out_penalty_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakoutpenaltysetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breakoutpenaltysetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakoutpenaltysetting',
            name='leave_type_to_reduce',
            field=models.ForeignKey(help_text='Select a leave type to reduce penalty days from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='break_out_penalty_settings', to='leave.LeaveType'),
        ),
        migrations.AddField(
            model_name='breakoutpenaltysetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breakoutpenaltysetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakoutpenaltysetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_out_penalty_settings', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='attendanceusermap',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceusermap_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceusermap',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceusermap_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceusermap',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.IndividualAttendanceSetting'),
        ),
        migrations.AddField(
            model_name='attendanceusermap',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.AttendanceSource'),
        ),
        migrations.AddField(
            model_name='attendancesource',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendancesource_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancesource',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendancesource_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceentrycache',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceentrycache_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceentrycache',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceentrycache_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceentrycache',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_cache', to='attendance.AttendanceSource'),
        ),
        migrations.AddField(
            model_name='attendanceadjustmenthistory',
            name='action_performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceadjustmenthistory',
            name='action_performed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceadjustmenthistory',
            name='adjustment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_histories', to='attendance.AttendanceAdjustment'),
        ),
        migrations.AddField(
            model_name='attendanceadjustmenthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceadjustmenthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceadjustmenthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceadjustmenthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceadjustment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceadjustment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_requests', to='attendance.TimeSheet'),
        ),
        migrations.AlterUniqueTogether(
            name='worktiming',
            unique_together={('work_day', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='workshift',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='webattendancefilter',
            unique_together={('setting', 'allow', 'cidr')},
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('timesheet_user', 'work_shift', 'work_time', 'timesheet_for')},
        ),
        migrations.AlterUniqueTogether(
            name='credithoursetting',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='attendanceusermap',
            unique_together={('bio_user_id', 'source'), ('setting', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='attendanceentrycache',
            unique_together={('source', 'bio_id', 'timestamp')},
        ),
    ]
