# Generated by Django 2.2.11 on 2021-02-19 06:22

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0003_create_materialize_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShiftLegend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('legend_text', models.CharField(max_length=3, validators=[irhrs.core.validators.validate_title])),
                ('legend_color', models.CharField(max_length=9, validators=[irhrs.core.validators.validate_is_hex_color])),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_workshiftlegend_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_workshiftlegend_modified', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_shift_legend', to='attendance.WorkShift')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
