# Generated by Django 2.2.11 on 2021-02-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_timesheetroster'),
        ('attendance', '0004_workshiftlegend'),
    ]

    operations = [
    ]
