# Generated by Django 2.2.11 on 2021-03-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_merge_20210222_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimesetting',
            name='calculate_overtime_in_slots',
            field=models.NullBooleanField(help_text='Allow users to define slots in Overtime Setting?'),
        ),
        migrations.AddField(
            model_name='overtimesetting',
            name='slot_behavior_for_remainder',
            field=models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down'), ('const', 'constant')], max_length=10),
        ),
        migrations.AddField(
            model_name='overtimesetting',
            name='slot_duration_in_minutes',
            field=models.IntegerField(help_text='The slots for overtime calculation in minutes.', null=True),
        ),
    ]
