# Generated by Django 2.2.11 on 2021-03-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20210303_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimesetting',
            name='slot_duration_in_minutes',
            field=models.PositiveSmallIntegerField(help_text='The slots for overtime calculation in minutes.', null=True),
        ),
    ]
