# Generated by Django 2.2.11 on 2021-03-19 14:52

from django.db import migrations, models
import django.db.models.deletion
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20210316_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceadjustment',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete')], default='add', max_length=15),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='category',
            field=models.CharField(blank=True, choices=[('Tea Break', 'Tea Break'), ('Client Visit', 'Client Visit'), ('Lunch Break', 'Lunch Break'), ('Meeting', 'Meeting'), ('Personal Break', 'Personal Break'), ('Others', 'Others'), ('Punch In', 'Punch In'), ('Punch Out', 'Punch Out')], max_length=15),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='timesheet_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='attendance.TimeSheetEntry'),
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='timestamp',
            field=models.DateTimeField(null=True, validators=[irhrs.core.validators.validate_past_datetime]),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='unpaid_break_hours',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='worked_hours',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='remark_category',
            field=models.CharField(choices=[('Tea Break', 'Tea Break'), ('Client Visit', 'Client Visit'), ('Lunch Break', 'Lunch Break'), ('Meeting', 'Meeting'), ('Personal Break', 'Personal Break'), ('Others', 'Others'), ('Punch In', 'Punch In'), ('Punch Out', 'Punch Out')], db_index=True, default='Others', max_length=30),
        ),
        migrations.AlterField(
            model_name='timesheetentryapproval',
            name='remark_category',
            field=models.CharField(choices=[('Tea Break', 'Tea Break'), ('Client Visit', 'Client Visit'), ('Lunch Break', 'Lunch Break'), ('Meeting', 'Meeting'), ('Personal Break', 'Personal Break'), ('Others', 'Others'), ('Punch In', 'Punch In'), ('Punch Out', 'Punch Out')], db_index=True, default='Others', max_length=30),
        ),
    ]
