# Generated by Django 2.2.11 on 2021-04-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210211_1614'),
        ('attendance', '0009_auto_20210428_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetuserpenalty',
            name='fiscal_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_penalties', to='organization.FiscalYearMonth'),
        ),
        migrations.AlterField(
            model_name='timesheetuserpenalty',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Generated', max_length=12),
        ),
        migrations.AlterField(
            model_name='timesheetuserpenaltystatushistory',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], max_length=12),
        ),
    ]
