# Generated by Django 2.2.11 on 2021-05-07 08:34

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_merge_20210505_1632'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0010_auto_20210429_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakoutpenaltysetting',
            name='leave_type_to_reduce',
        ),
        migrations.RemoveField(
            model_name='breakoutpenaltysetting',
            name='reduction_type',
        ),
        migrations.AddField(
            model_name='breakoutpenaltysetting',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breakoutpenaltysetting',
            name='title',
            field=models.CharField(default='Default', max_length=255, validators=[irhrs.core.validators.validate_title]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BreakoutPenaltyLeaveDeductionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breakoutpenaltyleavedeductionsetting_created', to=settings.AUTH_USER_MODEL)),
                ('leave_type_to_reduce', models.ForeignKey(help_text='Select a leave type to reduce penalty days from.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leave.LeaveType')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_breakoutpenaltyleavedeductionsetting_modified', to=settings.AUTH_USER_MODEL)),
                ('penalty_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types_to_reduce', to='attendance.BreakOutPenaltySetting')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('penalty_setting', 'order')},
            },
        ),
    ]
