# Generated by Django 2.2.11 on 2021-05-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20210507_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakoutpenaltyleavedeductionsetting',
            options={'ordering': ('-created_at', '-modified_at')},
        ),
        migrations.AlterUniqueTogether(
            name='breakoutpenaltyleavedeductionsetting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='breakoutpenaltyleavedeductionsetting',
            name='order',
        ),
    ]
