# Generated by Django 2.2.11 on 2021-05-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20210507_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualattendancesetting',
            name='penalty_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_settings', to='attendance.BreakOutPenaltySetting'),
        ),
    ]
