# Generated by Django 2.2.11 on 2021-05-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_individualattendancesetting_penalty_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetPenaltyToPayroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_on', models.DateTimeField()),
                ('days', models.PositiveIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('user_penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='attendance.TimeSheetUserPenalty')),
            ],
        ),
    ]
