# Generated by Django 2.2.11 on 2021-05-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_timesheetpenaltytopayroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetpenaltytopayroll',
            name='days',
            field=models.FloatField(),
        ),
    ]
