# Generated by Django 2.2.11 on 2021-05-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20210518_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimesetting',
            name='actual_ot_if_actual_gt_approved_ot',
            field=models.NullBooleanField(db_column='max_worked_approved', help_text='Expanded: Actual Overtime If Actual Overtime is greater Than Approved Overtime.FUNC: MAX(worked_hours, approved_hours)'),
        ),
    ]
