# Generated by Django 2.2.11 on 2021-06-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_overtimesetting_actual_ot_if_actual_gt_approved_ot'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualattendancesetting',
            name='enable_supervisor_notification',
            field=models.BooleanField(default=False),
        ),
    ]
