# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_individualattendancesetting_enable_supervisor_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete')], db_index=True, default='add', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='category',
            field=models.CharField(blank=True, choices=[('Tea Break', 'Tea Break'), ('Client Visit', 'Client Visit'), ('Lunch Break', 'Lunch Break'), ('Meeting', 'Meeting'), ('Personal Break', 'Personal Break'), ('Others', 'Others'), ('Punch In', 'Punch In'), ('Punch Out', 'Punch Out')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='attendanceadjustment',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], db_index=True, default='Requested', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendanceadjustmenthistory',
            name='action_performed',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='credithourdeleterequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Declined', 'Declined')], db_index=True, default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='credithourdeleterequesthistory',
            name='action_performed',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Declined', 'Declined')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='credithourrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Declined', 'Declined')], db_index=True, default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='credithourrequesthistory',
            name='action_performed',
            field=models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Confirmed', 'Confirmed')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='credithoursetting',
            name='deduct_credit_hour_after_for',
            field=models.CharField(choices=[('punch_in', 'Punch In Only'), ('punch_out', 'Punch Out Only'), ('both', 'Both'), ('neither', 'Neither')], db_index=True, default='neither', help_text='Generate credit to calculate only after criteria deductedEg: If `True`: 16 min will calculate 1 min; if `False`, will generate 16', max_length=20),
        ),
        migrations.AlterField(
            model_name='credithoursetting',
            name='expires_after_unit',
            field=models.CharField(blank=True, choices=[('d', 'Days'), ('m', 'Months'), ('y', 'Years')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='credithourtimesheetentry',
            name='status',
            field=models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Confirmed', 'Confirmed')], db_index=True, default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='individualworkinghour',
            name='working_hours_duration',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='overtimeclaim',
            name='status',
            field=models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Confirmed', 'Confirmed')], db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='overtimeclaimhistory',
            name='action_performed',
            field=models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Confirmed', 'Confirmed')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='overtimerate',
            name='rate_type',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Offday', 'Offday'), ('Workday', 'Workday'), ('Leave', 'Leave')], db_index=True, default='Workday', max_length=25),
        ),
        migrations.AlterField(
            model_name='overtimesetting',
            name='deduct_overtime_after_for',
            field=models.CharField(choices=[('punch_in', 'Punch In Only'), ('punch_out', 'Punch Out Only'), ('both', 'Both'), ('neither', 'Neither')], db_index=True, default='neither', help_text='Generate overtime to calculate only after criteria deducted', max_length=20),
        ),
        migrations.AlterField(
            model_name='overtimesetting',
            name='expires_after_unit',
            field=models.CharField(blank=True, choices=[('d', 'Days'), ('m', 'Months'), ('y', 'Years')], db_index=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='overtimesetting',
            name='overtime_after_holiday',
            field=models.CharField(choices=[('both', 'Generate Both'), ('deduction', 'Generate After Deduction'), ('no', 'No Overtime')], db_column='overtime_holiday', db_index=True, default='both', help_text='Deduct the hours consumed by compensatory leave and generate overtime for holiday.', max_length=20),
        ),
        migrations.AlterField(
            model_name='overtimesetting',
            name='overtime_after_offday',
            field=models.CharField(choices=[('both', 'Generate Both'), ('deduction', 'Generate After Deduction'), ('no', 'No Overtime')], db_column='overtime_compensatory', db_index=True, default='both', help_text='Deduct the hours consumed by compensatory leave and generate overtime', max_length=20),
        ),
        migrations.AlterField(
            model_name='overtimesetting',
            name='overtime_applicable_only_after',
            field=models.CharField(choices=[('both', 'Both'), ('either', 'Either')], db_index=True, default='both', max_length=20),
        ),
        migrations.AlterField(
            model_name='overtimesetting',
            name='slot_behavior_for_remainder',
            field=models.CharField(blank=True, choices=[('up', 'up'), ('down', 'down'), ('const', 'constant')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='penaltyrule',
            name='calculation_type',
            field=models.CharField(choices=[('frequency', 'Frequency'), ('duration', 'Duration')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='penaltyrule',
            name='penalty_counter_unit',
            field=models.CharField(choices=[('days', 'Days'), ('month', 'Month')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='preapprovalovertime',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], db_index=True, default='Requested', max_length=30),
        ),
        migrations.AlterField(
            model_name='preapprovalovertimehistory',
            name='action_performed',
            field=models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Confirmed', 'Confirmed')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hour_off_coefficient',
            field=models.CharField(blank=True, choices=[('Time Off', 'Time Off'), ('Credit Hour', 'Credit Hour'), ('credit-time-off', 'Credit Hour & Time Off')], db_index=True, help_text='Indication of Time Off or Credit Hour Used.', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='leave_coefficient',
            field=models.CharField(choices=[('First Half', 'First Half'), ('Second Half', 'Second Half'), ('Full Leave', 'Full Leave'), ('No Leave', 'No Leave')], db_index=True, default='No Leave', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheetapproval',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined')], db_index=True, default='Requested', max_length=16),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='category',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Early In', 'Early In'), ('Timely In', 'Timely In'), ('Late In', 'Late In'), ('Early Out', 'Early Out'), ('Timely Out', 'Timely Out'), ('Late Out', 'Late Out')], db_index=True, default='Uncategorized', max_length=15),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='entry_method',
            field=models.CharField(choices=[('Device', 'Device'), ('Web App', 'Web App'), ('Mobile App', 'Mobile App'), ('RFID Card', 'RFID Card'), ('Password', 'Password'), ('Att Adjustment', 'Attendance Adjustment'), ('Other', 'Other'), ('Import', 'Import'), ('Travel Att', 'Travel Attendance')], db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetentryapproval',
            name='category',
            field=models.CharField(choices=[('Uncategorized', 'Uncategorized'), ('Early In', 'Early In'), ('Timely In', 'Timely In'), ('Late In', 'Late In'), ('Early Out', 'Early Out'), ('Timely Out', 'Timely Out'), ('Late Out', 'Late Out')], db_index=True, default='Uncategorized', max_length=15),
        ),
        migrations.AlterField(
            model_name='timesheetentryapproval',
            name='entry_method',
            field=models.CharField(choices=[('Device', 'Device'), ('Web App', 'Web App'), ('Mobile App', 'Mobile App'), ('RFID Card', 'RFID Card'), ('Password', 'Password'), ('Att Adjustment', 'Attendance Adjustment'), ('Other', 'Other'), ('Import', 'Import'), ('Travel Att', 'Travel Attendance')], db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetentryapproval',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined')], db_index=True, default='Requested', max_length=10),
        ),
        migrations.AlterField(
            model_name='timesheetregistrationreportsettings',
            name='fiscal_year_category',
            field=models.CharField(choices=[('global', 'Global'), ('leave', 'Leave')], db_index=True, help_text='When approval required is set, choose fiscal year type to use while selecting 1st day of month.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetreportrequest',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Forwarded', 'Forwarded'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheetreportrequesthistory',
            name='action',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Forwarded', 'Forwarded'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheetuserpenalty',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], db_index=True, default='Generated', max_length=12),
        ),
        migrations.AlterField(
            model_name='timesheetuserpenaltystatushistory',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='travelattendancedeleterequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], db_index=True, help_text='Status of this travel request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelattendancedeleterequesthistory',
            name='action_performed',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], db_index=True, help_text='Status of this travel request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelattendancerequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], db_index=True, help_text='Status of this travel request.', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelattendancerequest',
            name='working_time',
            field=models.CharField(choices=[('First Half', 'First Half'), ('Second Half', 'Second Half'), ('Full Day', 'Full Day')], db_index=True, default='Full Day', help_text='If the user decides to work first half, second half, or full time.', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelattendancerequesthistory',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Forwarded', 'Forwarded'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Cancelled', 'Cancelled')], db_index=True, help_text='Status of this travel request.', max_length=20),
        ),
    ]
