# Generated by Django 3.2.12 on 2022-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_auto_20220307_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetregistrationreportsettings',
            name='headers',
            field=models.JSONField(help_text='Header field to display name map'),
        ),
        migrations.AlterField(
            model_name='timesheetregistrationreportsettings',
            name='leave_legend',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='timesheetregistrationreportsettings',
            name='primary_legend',
            field=models.JSONField(help_text='Primary legend configuration'),
        ),
        migrations.AlterField(
            model_name='timesheetreportrequest',
            name='report_data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='timesheetreportrequest',
            name='settings_data',
            field=models.JSONField(),
        ),
    ]
