# Generated by Django 3.2.12 on 2023-02-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_credithourrequest_credit_hour_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualattendancesetting',
            name='weekly_attendance_report_email',
            field=models.BooleanField(default=False),
        ),
    ]
