# Generated by Django 3.2.12 on 2023-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_credithourrequest_credit_hour_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='working_remotely',
            field=models.BooleanField(default=False),
        ),
    ]
