# Generated by Django 3.2.12 on 2023-03-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_individualattendancesetting_weekly_attendance_report_email'),
        ('attendance', '0022_timesheet_working_remotely'),
    ]

    operations = [
    ]
