# Generated by Django 3.2.12 on 2023-03-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_merge_20230303_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesource',
            name='name',
            field=models.CharField(help_text='Set name to identify the device uniquely.', max_length=50, unique=True),
        ),
    ]
