# Generated by Django 3.2.12 on 2024-01-30 04:23

import cuser.fields
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_alter_emailnotificationsetting_email_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0024_alter_attendancesource_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHeadingReportSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('headings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('day', 'day'), ('leave_coefficient', 'leave_coefficient'), ('logs', 'logs'), ('expected_punch_in', 'expected_punch_in'), ('expected_punch_out', 'expected_punch_out'), ('punch_in_category', 'punch_in_category'), ('punch_out_category', 'punch_out_category'), ('total_lost_hours', 'total_lost_hours'), ('break_in_out_lost_hours', 'break_in_out_lost_hours'), ('overtime', 'overtime'), ('approved_overtime', 'approved_overtime'), ('confirmed_overtime', 'confirmed_overtime'), ('worked_hours', 'worked_hours'), ('expected_work_hours', 'expected_work_hours'), ('coefficient', 'coefficient')], max_length=30), size=None)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceheadingreportsetting_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_attendanceheadingreportsetting_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organization.organization')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
