# Generated by Django 3.2.12 on 2024-03-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_attendanceheadingreportsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='entry_method',
            field=models.CharField(choices=[('Device', 'Device'), ('Web App', 'Web App'), ('Mobile App', 'Mobile App'), ('RFID Card', 'RFID Card'), ('Password', 'Password'), ('Att Adjustment', 'Attendance Adjustment'), ('Other', 'Other'), ('Import', 'Import'), ('Travel Att', 'Travel Attendance'), ('Training Att', 'Training Attendance')], db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetentryapproval',
            name='entry_method',
            field=models.CharField(choices=[('Device', 'Device'), ('Web App', 'Web App'), ('Mobile App', 'Mobile App'), ('RFID Card', 'RFID Card'), ('Password', 'Password'), ('Att Adjustment', 'Attendance Adjustment'), ('Other', 'Other'), ('Import', 'Import'), ('Travel Att', 'Travel Attendance'), ('Training Att', 'Training Attendance')], db_index=True, max_length=15, null=True),
        ),
    ]
