# Generated by Django 2.2.11 on 2021-02-11 10:29

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import irhrs.core.fields.fields
import irhrs.core.utils.common
import irhrs.core.validators
import irhrs.organization.models.other
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(choices=[('worklog', 'worklog'), ('payroll', 'payroll'), ('assessment', 'assessment'), ('training', 'training'), ('recruitment', 'recruitment'), ('reimbursement', 'reimbursement')], max_length=25)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedEquipmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Idle', 'Idle'), ('Used', 'Used'), ('Damaged', 'Damaged')], default='Damaged', max_length=16)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('critical_days', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(limit_value=0)])),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentJobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=150, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('title', 'organization'),
            },
        ),
        migrations.CreateModel(
            name='EmploymentLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=150, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True, max_length=600)),
                ('code', models.CharField(blank=True, max_length=50, validators=[irhrs.core.validators.validate_title])),
                ('order_field', models.FloatField(validators=[irhrs.core.validators.validate_natural_number, django.core.validators.MaxValueValidator(200)])),
                ('is_archived', models.BooleanField(default=False)),
                ('scale_max', models.PositiveSmallIntegerField(validators=[irhrs.core.validators.MinMaxValueValidator(max_value=100, min_value=1)])),
                ('auto_increment', models.BooleanField(default=False, help_text='Enabling this flag will add a change type automatically.')),
                ('auto_add_step', models.PositiveSmallIntegerField(help_text='Add this value automatically after certain period. 1-100', null=True, validators=[irhrs.core.validators.MinMaxValueValidator(max_value=100, min_value=1)])),
                ('changes_on_fiscal', models.NullBooleanField()),
                ('frequency', models.PositiveSmallIntegerField(help_text='Period range 1-3000', null=True, validators=[irhrs.core.validators.MinMaxValueValidator(max_value=3000, min_value=1)])),
                ('duration', models.CharField(blank=True, choices=[('d', 'Days'), ('m', 'Months'), ('y', 'Years')], help_text='Day, Month or Year', max_length=1)),
                ('level', models.CharField(blank=True, choices=[('top_management', 'Top Management'), ('management', 'Management'), ('officer', 'Officer'), ('assistant', 'Assistant')], default='', max_length=15)),
            ],
            options={
                'ordering': ('order_field',),
            },
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=150, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True)),
                ('is_contract', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('title', 'organization'),
            },
        ),
        migrations.CreateModel(
            name='EmploymentStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=150, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('title', 'organization'),
            },
        ),
        migrations.CreateModel(
            name='EquipmentAssignedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assigned_date', models.DateField(default=irhrs.core.utils.common.get_today, validators=[irhrs.core.validators.validate_past_date_or_today])),
                ('released_date', models.DateField(null=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(help_text='Name for the Fiscal Year', max_length=100)),
                ('start_at', models.DateField(help_text='Start Date')),
                ('end_at', models.DateField(help_text='End Date')),
                ('description', models.TextField(help_text='Description about the Fiscal year')),
                ('applicable_from', models.DateField(help_text='Fiscal Year settings to be applicable from')),
                ('applicable_to', models.DateField(help_text='Fiscal Year settings to be applicable Upto')),
                ('category', models.CharField(choices=[('global', 'Global'), ('leave', 'Leave')], default='global', max_length=32)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalYearMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('month_index', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Order of the month in fiscal year')),
                ('display_name', models.CharField(help_text='Display name of the Month', max_length=20)),
                ('start_at', models.DateField(help_text='start date of month')),
                ('end_at', models.DateField(help_text='end date of month')),
            ],
            options={
                'ordering': ('month_index',),
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=150, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[irhrs.core.validators.validate_image_size, irhrs.core.validators.validate_image_file_extension])),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HolidayRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('lower_age', models.PositiveSmallIntegerField(null=True, validators=[irhrs.core.validators.validate_user_age])),
                ('upper_age', models.PositiveSmallIntegerField(null=True, validators=[irhrs.core.validators.validate_user_age])),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSkillAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True, max_length=600)),
                ('ksa_type', models.CharField(choices=[('knowledge', 'Knowledge'), ('skill', 'Skill'), ('ability', 'Ability'), ('other_attributes', 'Other Attributes')], default='knowledge', max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, validators=[irhrs.core.validators.validate_invalid_chars])),
                ('description', models.TextField(blank=True, max_length=100000)),
                ('location', models.CharField(max_length=500, validators=[irhrs.core.validators.validate_address])),
                ('floor', models.CharField(max_length=100, validators=[irhrs.core.validators.validate_invalid_chars])),
                ('area', models.CharField(blank=True, max_length=150)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[irhrs.core.validators.validate_image_file_extension])),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingRoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('booked_from', models.DateTimeField()),
                ('booked_to', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('message', models.TextField(help_text='Message to display for the users.')),
                ('published', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplateMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('active_status', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=irhrs.organization.models.other.default_active_status, size=None)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(help_text='Name of the Organization/Company.', max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('abbreviation', models.CharField(help_text='Short form of the Organization/Company.', max_length=15)),
                ('about', models.TextField(max_length=6000)),
                ('ownership', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Public', 'Public'), ('Non-profit', 'Non-profit')], max_length=15)),
                ('size', models.CharField(choices=[('1 - 10 employees', '1 - 10 employees'), ('10 - 50 employees', '10 - 50 employees'), ('50 - 100 employees', '50 - 100 employees'), ('100 - 200 employees', '100 - 200 employees'), ('200 - 500 employees', '200 - 500 employees'), ('500 - 1000 employees', '500 - 1000 employees'), ('1000+ employees', '1000+ employees'), ('Confidential', 'Confidential')], help_text='Size of the Organization/Company', max_length=25)),
                ('website', models.URLField(blank=True)),
                ('established_on', models.DateField(null=True, validators=[irhrs.core.validators.validate_past_date])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contacts', irhrs.core.fields.fields.JSONTextField(validators=[irhrs.core.validators.validate_json_contact])),
                ('registration_number', models.CharField(blank=True, max_length=50, validators=[irhrs.core.validators.validate_has_digit, irhrs.core.validators.validate_invalid_chars])),
                ('vat_pan_number', models.CharField(blank=True, max_length=50, validators=[irhrs.core.validators.validate_has_digit, irhrs.core.validators.validate_invalid_chars])),
            ],
            options={
                'ordering': ('created_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('mailing_address', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#42a5f5', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('header_logo', models.ImageField(blank=True, upload_to='organization/header-logo/', validators=[irhrs.core.validators.validate_image_file_extension])),
                ('logo', models.ImageField(blank=True, upload_to='organization/logo/', validators=[irhrs.core.validators.validate_image_file_extension])),
                ('background_image', models.ImageField(blank=True, upload_to='organization/bg-image/', validators=[irhrs.core.validators.validate_image_file_extension])),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(blank=True, max_length=150, unique=True, validators=[irhrs.core.validators.validate_has_digit, irhrs.core.validators.validate_invalid_chars])),
                ('contacts', irhrs.core.fields.fields.JSONTextField(validators=[irhrs.core.validators.validate_json_contact])),
                ('branch', models.CharField(max_length=150, null=True, validators=[irhrs.core.validators.validate_title])),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('contact_person', irhrs.core.fields.fields.JSONTextField(blank=True, default={}, validators=[irhrs.core.validators.validate_contact_person])),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('address', models.CharField(db_index=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(help_text='Name of the branch of the organization', max_length=200, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True)),
                ('contacts', irhrs.core.fields.fields.JSONTextField(validators=[irhrs.core.validators.validate_json_contact])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('code', models.CharField(max_length=15, null=True, unique=True)),
                ('mailing_address', models.TextField(blank=True, max_length=255)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=150, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True)),
                ('extension_number', models.PositiveSmallIntegerField(null=True, unique=True, validators=[irhrs.core.validators.validate_natural_number])),
                ('strategies', models.TextField(blank=True)),
                ('action_plans', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(help_text='Title of the organization document.', max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(null=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'odt', 'pdf', 'xls', 'xlsx', 'ods', 'ppt', 'pptx', 'txt', 'tif', 'tiff', 'jif', 'jfif', 'jp2', 'jpx', 'j2k', 'j2c', 'fpx', 'pcd', 'psd', 'rtf', 'gif', 'jpeg', 'jpg', 'png'])])),
                ('is_archived', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('is_downloadable', models.BooleanField(default=True)),
                ('for_resignation', models.BooleanField(default=False)),
                ('document_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=150, validators=[irhrs.core.validators.validate_title])),
                ('code', models.CharField(max_length=50)),
                ('brand_name', models.CharField(blank=True, max_length=150)),
                ('amount', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchased_date', models.DateField(null=True, validators=[irhrs.core.validators.validate_past_date_or_today])),
                ('service_order', models.CharField(blank=True, max_length=50)),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=16)),
                ('assigned_to', models.CharField(choices=[('User', 'User'), ('Division / Branch', 'Division / Branch'), ('Meeting Room', 'Meeting Room')], max_length=50)),
                ('status', models.CharField(choices=[('Idle', 'Idle'), ('Used', 'Used'), ('Damaged', 'Damaged')], default='Idle', max_length=16)),
                ('specifications', models.TextField(blank=True, max_length=100000)),
                ('acquired_date', models.DateField(auto_now_add=True, null=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('released_remark', models.CharField(blank=True, choices=[('Permanent Damage', 'Permanent Damage'), ('Released', 'Released'), ('Transfer', 'Transfer'), ('Others', 'Others')], max_length=16, null=True)),
                ('equipment_picture', sorl.thumbnail.fields.ImageField(blank=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[irhrs.core.validators.validate_image_file_extension])),
                ('remark', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationEthics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True, max_length=600)),
                ('moral', models.CharField(choices=[('Do', 'Do'), ('Dont', "Don't"), ('Rules', 'Rules'), ('Regulation', 'Regulation')], default='Do', max_length=15)),
                ('published', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('attachment', models.FileField(null=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'odt', 'pdf', 'xls', 'xlsx', 'ods', 'ppt', 'pptx', 'txt', 'tif', 'tiff', 'jif', 'jfif', 'jp2', 'jpx', 'j2k', 'j2c', 'fpx', 'pcd', 'psd', 'rtf', 'gif', 'jpeg', 'jpg', 'png'])])),
                ('is_downloadable', models.BooleanField(default=True)),
                ('document_text', models.TextField(blank=True, max_length=10000)),
            ],
            options={
                'ordering': ('title', 'moral'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationMission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(help_text='Short title on the mission of the organization/company.', max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True, help_text='Description on the mission.')),
                ('order_field', models.FloatField(default=1, validators=[irhrs.core.validators.validate_natural_number])),
            ],
            options={
                'ordering': ('order_field',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.TextField(validators=[irhrs.core.validators.validate_title])),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('can_switch', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
