# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irhrs.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20210211_1614'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_userorganization_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_userorganization_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='userorganization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationvision',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationvision_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationvision',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationvision_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationvision',
            name='organization',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vision', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationmission',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationmission_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmission',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationmission_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmission',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationmission',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_missions', to='organization.OrganizationMission'),
        ),
        migrations.AddField(
            model_name='organizationethics',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationethics_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationethics',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationethics_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationethics',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ethics', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationethics',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_ethics', to='organization.OrganizationEthics'),
        ),
        migrations.AddField(
            model_name='organizationequipment',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='common.EquipmentCategory'),
        ),
        migrations.AddField(
            model_name='organizationequipment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationequipment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationequipment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationequipment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationequipment',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='category',
            field=models.ForeignKey(help_text='Document Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_documents', to='common.DocumentCategory', validators=[irhrs.core.validators.DocumentTypeValidator(association_type='Organization')]),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationdocument_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationdocument_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='org_documents', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationdivision',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationdivision_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationdivision',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationdivision',
            name='mission',
            field=models.ManyToManyField(to='organization.OrganizationMission'),
        ),
        migrations.AddField(
            model_name='organizationdivision',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationdivision_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationdivision',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationdivision',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_child', to='organization.OrganizationDivision'),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='branch_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationbranch_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationbranch_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationbank',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_banks', to='common.Bank'),
        ),
        migrations.AddField(
            model_name='organizationbank',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationbank_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationbank',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationbank_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationbank',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationappearance',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationappearance_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationappearance',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationappearance_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationappearance',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appearance', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationaddress_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organizationaddress_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='admin_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organization_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='common.Industry'),
        ),
        migrations.AddField(
            model_name='organization',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_organization_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_head_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organizations', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='notificationtemplatemap',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_notificationtemplatemap_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplatemap',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_notificationtemplatemap_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplatemap',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='notificationtemplatemap',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.NotificationTemplate'),
        ),
        migrations.AddField(
            model_name='messagetouser',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_messagetouser_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetouser',
            name='message_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetouser',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_messagetouser_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroomstatus',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_meetingroomstatus_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroomstatus',
            name='meeting_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='organization.MeetingRoom'),
        ),
        migrations.AddField(
            model_name='meetingroomstatus',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_meetingroomstatus_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroomattachment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_meetingroomattachment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroomattachment',
            name='meeting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='organization.MeetingRoom'),
        ),
        migrations.AddField(
            model_name='meetingroomattachment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_meetingroomattachment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_rooms', to='organization.OrganizationBranch'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_meetingroom_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_meetingroom_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_rooms', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='knowledgeskillability',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_knowledgeskillability_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeskillability',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_knowledgeskillability_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgeskillability',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksa', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='holidayrule',
            name='branch',
            field=models.ManyToManyField(related_name='holiday_branch', to='organization.OrganizationBranch'),
        ),
        migrations.AddField(
            model_name='holidayrule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_holidayrule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holidayrule',
            name='division',
            field=models.ManyToManyField(related_name='holiday_division', to='organization.OrganizationDivision'),
        ),
        migrations.AddField(
            model_name='holidayrule',
            name='ethnicity',
            field=models.ManyToManyField(limit_choices_to={'category': 'Ethnicity'}, related_name='holiday_ethnicity', to='common.ReligionAndEthnicity'),
        ),
        migrations.AddField(
            model_name='holidayrule',
            name='holiday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule', to='organization.Holiday'),
        ),
        migrations.AddField(
            model_name='holidayrule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_holidayrule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holidayrule',
            name='religion',
            field=models.ManyToManyField(limit_choices_to={'category': 'Religion'}, related_name='holiday_religion', to='common.ReligionAndEthnicity'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.HolidayCategory'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_holiday_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_holiday_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='fiscalyearmonth',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_fiscalyearmonth_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyearmonth',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_months', to='organization.FiscalYear'),
        ),
        migrations.AddField(
            model_name='fiscalyearmonth',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_fiscalyearmonth_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_fiscalyear_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_fiscalyear_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='equipmentassignedto',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='organization.OrganizationBranch'),
        ),
        migrations.AddField(
            model_name='equipmentassignedto',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_equipmentassignedto_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentassignedto',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='organization.OrganizationDivision'),
        ),
        migrations.AddField(
            model_name='equipmentassignedto',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipments', to='organization.OrganizationEquipment'),
        ),
        migrations.AddField(
            model_name='equipmentassignedto',
            name='meeting_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='organization.MeetingRoom'),
        ),
        migrations.AddField(
            model_name='equipmentassignedto',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_equipmentassignedto_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentassignedto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentstep',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_employmentstep_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentstep',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_employmentstep_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentstep',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_employmentstatus_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_employmentstatus_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_status', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='employmentlevel',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_employmentlevel_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentlevel',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_employmentlevel_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentlevel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_levels', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='employmentjobtitle',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_employmentjobtitle_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentjobtitle',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_employmentjobtitle_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentjobtitle',
            name='organization',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='contractsettings',
            name='organization',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contract_settings', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='assignedequipmentstatus',
            name='assigned_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status', to='organization.EquipmentAssignedTo'),
        ),
        migrations.AddField(
            model_name='assignedequipmentstatus',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedequipmentstatus',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_assignedequipmentstatus_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedequipmentstatus',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_assignedequipmentstatus_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationsettings',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_settings', to='organization.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationvision',
            unique_together={('organization', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationethics',
            unique_together={('organization', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationdocument',
            unique_together={('organization', 'title', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationdivision',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationbranch',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='knowledgeskillability',
            unique_together={('name', 'organization', 'ksa_type')},
        ),
        migrations.AlterUniqueTogether(
            name='employmentstatus',
            unique_together={('title', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='employmentlevel',
            unique_together={('organization', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='employmentjobtitle',
            unique_together={('title', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationsettings',
            unique_together={('organization', 'application')},
        ),
    ]
