# Generated by Django 2.2.11 on 2021-05-03 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdocument',
            name='acknowledgements',
            field=models.ManyToManyField(help_text='Users who acknowledge this document will be kept here.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='require_acknowledgement',
            field=models.BooleanField(default=False),
        ),
    ]
