# Generated by Django 2.2.11 on 2021-04-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationequipment',
            name='status',
        ),
        migrations.AddField(
            model_name='organizationequipment',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipmentassignedto',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='organization.OrganizationEquipment'),
        ),
    ]
