# Generated by Django 2.2.11 on 2021-05-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210427_1503'),
        ('organization', '0003_auto_20210503_1617'),
    ]

    operations = [
    ]
