# Generated by Django 2.2.11 on 2021-05-10 12:03

from django.db import migrations, models
import irhrs.core.utils.common


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_merge_20210506_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentassignedto',
            name='assigned_date',
            field=models.DateField(default=irhrs.core.utils.common.get_today),
        ),
    ]
