# Generated by Django 2.2.11 on 2021-06-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_emailnotificationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationsetting',
            name='email_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Birthday Email'), (2, 'Anniversary Email'), (3, 'Holiday Email'), (4, 'When you are invited to an event/meeting'), (5, 'When an event/meeting, you are involved, is updated'), (6, 'When an event/meeting, you are involved, is updated')]),
        ),
    ]
