# Generated by Django 2.2.11 on 2021-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20210610_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationsetting',
            name='email_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Birthday Email'), (2, 'Anniversary Email'), (3, 'Holiday Email'), (4, 'When you are invited to an event/meeting'), (5, 'When an event/meeting, you are involved, is updated'), (6, 'When an event/meeting, you are involved, is cancelled'), (40, 'When an assessment is assigned/unassigned to a user.'), (41, 'When an user completes an assigned assessment(For HR Only)'), (42, "When an employee's expiry date is in critical date range(For HR only).")]),
        ),
    ]
