# Generated by Django 2.2.11 on 2021-06-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20210615_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationsetting',
            name='email_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Birthday Email'), (2, 'Anniversary Email'), (3, 'Holiday Email'), (4, 'When you are invited to an event/meeting'), (5, 'When an event/meeting, you are involved, is updated'), (6, 'When an event/meeting, you are involved, is cancelled'), (40, 'When an assessment is assigned/unassigned to a user.'), (41, 'When an user completes an assigned assessment(For HR Only)'), (42, "When an employee's expiry date is in critical date range(For HR only)."), (43, 'When a training is assigned/unassigned.'), (44, 'When a training is deleted/cancelled.'), (45, 'When a training is requested by user(For HR only).'), (47, 'When a training is acted upon.'), (46, 'When a training is updated.')]),
        ),
    ]
