# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20210623_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedequipmentstatus',
            name='status',
            field=models.CharField(choices=[('Idle', 'Idle'), ('Used', 'Used'), ('Damaged', 'Damaged')], db_index=True, default='Damaged', max_length=16),
        ),
        migrations.AlterField(
            model_name='employmentlevel',
            name='duration',
            field=models.CharField(blank=True, choices=[('d', 'Days'), ('m', 'Months'), ('y', 'Years')], db_index=True, help_text='Day, Month or Year', max_length=1),
        ),
        migrations.AlterField(
            model_name='employmentlevel',
            name='level',
            field=models.CharField(blank=True, choices=[('top_management', 'Top Management'), ('management', 'Management'), ('officer', 'Officer'), ('assistant', 'Assistant')], db_index=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='holidayrule',
            name='gender',
            field=models.CharField(choices=[('All', 'All'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='knowledgeskillability',
            name='ksa_type',
            field=models.CharField(choices=[('knowledge', 'Knowledge'), ('skill', 'Skill'), ('ability', 'Ability'), ('other_attributes', 'Other Attributes')], db_index=True, default='knowledge', max_length=22),
        ),
        migrations.AlterField(
            model_name='organizationequipment',
            name='assigned_to',
            field=models.CharField(choices=[('User', 'User'), ('Division / Branch', 'Division / Branch'), ('Meeting Room', 'Meeting Room')], db_index=True, max_length=50),
        ),
    ]
