# Generated by Django 2.2.11 on 2021-08-26 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20210629_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyearmonth',
            name='month_index',
            field=models.IntegerField(help_text='Order of the month in fiscal year', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
