# Generated by Django 2.2.11 on 2022-02-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_auto_20220120_1358'),
        ('organization', '0021_merge_20220127_1020'),
    ]

    operations = [
    ]
