# Generated by Django 2.2.11 on 2022-03-23 09:31
import json
import os

from django.db import migrations, models
import django.db.models.deletion
import irhrs.core.fields.fields
import irhrs.core.validators
from config import settings


def update_province_name(apps, schema_editor):
    Country = apps.get_model(
        "recruitment", "Country")
    Province = apps.get_model(
        "recruitment", "Province")

    with open(
        os.path.abspath(
            os.path.join(
                settings.PROJECT_DIR,
                'fixtures/commons/locations.json'
            )
        )
    ) as f:
        location_data = json.load(f)
        countries = location_data['countries']
        provinces = location_data['provinces']

    # seed country
    for country_data in countries:
        _id = country_data.pop('id')
        Country.objects.get_or_create(id=_id, defaults=country_data)

    # seed province
    for province in provinces:
        _id = province.pop('id')
        nepal = Country.objects.get(name="Nepal")
        province.update({"country": nepal})
        Province.objects.update_or_create(id=_id, defaults=province)


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20220117_1458'),
        ('organization', '0024_auto_20220208_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationbranch',
            name='country_ref',
            field=models.ForeignKey(default=603, on_delete=django.db.models.deletion.CASCADE, related_name='branch_countries', to='recruitment.Country'),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_provinces', to='recruitment.Province'),
        ),
        migrations.AddField(
            model_name='organizationbranch',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizationbranch',
            name='contacts',
            field=irhrs.core.fields.fields.JSONTextField(validators=[irhrs.core.validators.validate_json_contact_in_branch]),
        ),
        migrations.RunPython(update_province_name)
    ]
