# Generated by Django 3.2.12 on 2022-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_auto_20220208_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentlevel',
            name='changes_on_fiscal',
            field=models.BooleanField(null=True),
        ),
    ]
