# Generated by Django 3.2.12 on 2022-05-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_alter_employmentlevel_changes_on_fiscal'),
        ('organization', '0027_auto_20220419_1125'),
    ]

    operations = [
    ]
