# Generated by Django 3.2.12 on 2022-11-21 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0029_alter_emailnotificationsetting_email_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationsettings',
            options={'verbose_name_plural': 'Application Settings'},
        ),
        migrations.AlterModelOptions(
            name='assignedequipmentstatus',
            options={'verbose_name_plural': 'Assigned Equipment Status'},
        ),
        migrations.AlterModelOptions(
            name='contractsettings',
            options={'verbose_name_plural': 'Contract Settings'},
        ),
        migrations.AlterModelOptions(
            name='employmentstatus',
            options={'ordering': ('title', 'organization'), 'verbose_name_plural': 'Employment Status'},
        ),
        migrations.AlterModelOptions(
            name='equipmentassignedto',
            options={'verbose_name_plural': 'Equipment Assigned To'},
        ),
        migrations.AlterModelOptions(
            name='knowledgeskillability',
            options={'verbose_name_plural': 'Knowledge skill abilities'},
        ),
        migrations.AlterModelOptions(
            name='meetingroomstatus',
            options={'verbose_name_plural': 'Meeting Room Status'},
        ),
        migrations.AlterModelOptions(
            name='organizationaddress',
            options={'verbose_name_plural': 'Organization Address'},
        ),
        migrations.AlterModelOptions(
            name='organizationethics',
            options={'ordering': ('title', 'moral'), 'verbose_name_plural': 'Organization Ethics'},
        ),
        migrations.AlterUniqueTogether(
            name='organizationethics',
            unique_together={('organization', 'title', 'description')},
        ),
    ]
