# Generated by Django 3.2.12 on 2022-12-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_auto_20221121_0926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organizationethics',
            unique_together={('organization', 'title')},
        ),
    ]
