# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reimbursement', '0001_initial'),
        ('organization', '0002_auto_20210211_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementoptionsetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementoptionsetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementoptionsetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementoptionsetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementoptionsetting',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reimbursement.ReimbursementSetting'),
        ),
        migrations.AddField(
            model_name='settlementoption',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementoption_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementoption',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementoption_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementoption',
            name='settle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='reimbursement.ExpenseSettlement'),
        ),
        migrations.AddField(
            model_name='settlementhistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementhistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reimbursement.ExpenseSettlement'),
        ),
        migrations.AddField(
            model_name='settlementdocuments',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementdocuments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementdocuments',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementdocuments_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementdocuments',
            name='settle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reimbursement.ExpenseSettlement'),
        ),
        migrations.AddField(
            model_name='settlementapproval',
            name='acted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementapproval',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementapproval_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementapproval',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementapproval_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settlementapproval',
            name='settle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='reimbursement.ExpenseSettlement'),
        ),
        migrations.AddField(
            model_name='settlementapproval',
            name='user',
            field=models.ManyToManyField(related_name='settle_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reimbursementsetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_reimbursementsetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reimbursementsetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_reimbursementsetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reimbursementsetting',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_setting', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='expensesettlement',
            name='advance_expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='reimbursement.AdvanceExpenseRequest'),
        ),
        migrations.AddField(
            model_name='expensesettlement',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_expensesettlement_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesettlement',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_request_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesettlement',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_expensesettlement_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensesettlement',
            name='recipient',
            field=models.ManyToManyField(related_name='settlement_requests_to_act', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseapprovalsetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_expenseapprovalsetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseapprovalsetting',
            name='employee',
            field=models.ManyToManyField(related_name='expanse_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseapprovalsetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_expenseapprovalsetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenseapprovalsetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expanse_setting', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='advanceexpenserequesthistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequesthistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='reimbursement.AdvanceExpenseRequest'),
        ),
        migrations.AddField(
            model_name='advanceexpenserequestdocuments',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpenserequestdocuments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequestdocuments',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reimbursement.AdvanceExpenseRequest'),
        ),
        migrations.AddField(
            model_name='advanceexpenserequestdocuments',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpenserequestdocuments_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequestapproval',
            name='acted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_actors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequestapproval',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpenserequestapproval_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequestapproval',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='reimbursement.AdvanceExpenseRequest'),
        ),
        migrations.AddField(
            model_name='advanceexpenserequestapproval',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpenserequestapproval_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequestapproval',
            name='user',
            field=models.ManyToManyField(related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequest',
            name='associates',
            field=models.ManyToManyField(related_name='expense_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpenserequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_expense_request_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpenserequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advanceexpenserequest',
            name='recipient',
            field=models.ManyToManyField(related_name='advance_expense_requests_to_act', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='expenseapprovalsetting',
            unique_together={('organization', 'approval_level'), ('organization', 'supervisor_level')},
        ),
    ]
