# Generated by Django 2.2.11 on 2021-05-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesettlement',
            name='is_taxable',
            field=models.BooleanField(default=False),
        ),
    ]
