# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0003_expensesettlement_is_taxable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceexpenserequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], db_index=True, default='Requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='advanceexpenserequestapproval',
            name='role',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='advanceexpenserequestapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='expensesettlement',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], db_index=True, default='Requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='settlementapproval',
            name='role',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='settlementapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], db_index=True, max_length=25),
        ),
    ]
