# Generated by Django 2.2.11 on 2022-07-13 03:45

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_auto_20220707_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursementsetting',
            name='lodging_rate',
            field=models.FloatField(default=1.0, verbose_name=irhrs.core.validators.MinMaxValueValidator(0, 1)),
        ),
        migrations.AddField(
            model_name='reimbursementsetting',
            name='others_rate',
            field=models.FloatField(default=1.0, verbose_name=irhrs.core.validators.MinMaxValueValidator(0, 1)),
        ),
        migrations.AddField(
            model_name='reimbursementsetting',
            name='per_diem_rate',
            field=models.FloatField(default=1.0, verbose_name=irhrs.core.validators.MinMaxValueValidator(0, 1)),
        ),
    ]
