# Generated by Django 3.2.12 on 2022-07-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_auto_20220307_1154'),
        ('reimbursement', '0005_auto_20220707_1050'),
    ]

    operations = [
    ]
