# Generated by Django 2.2.11 on 2022-07-26 03:14

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0027_auto_20220419_1125'),
        ('reimbursement', '0006_auto_20220713_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementApprovalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approve_by', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], default='Supervisor', max_length=10)),
                ('supervisor_level', models.CharField(blank=True, choices=[('All', 'All'), ('First', '1st Level'), ('Second', '2nd Level'), ('Third', '3rd Level')], max_length=6, null=True)),
                ('approval_level', models.IntegerField()),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementapprovalsetting_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ManyToManyField(related_name='settlement_settings', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_settlementapprovalsetting_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_setting', to='organization.Organization')),
            ],
            options={
                'abstract': False,
                'unique_together': {('organization', 'supervisor_level'), ('organization', 'approval_level')},
            },
        ),
    ]
