# Generated by Django 3.2.12 on 2022-07-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0006_merge_0005_auto_20220307_1154_0005_auto_20220707_1050'),
        ('reimbursement', '0007_settlementapprovalsetting'),
    ]

    operations = [
    ]
