# Generated by Django 2.2.11 on 2022-08-24 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0007_settlementapprovalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseapprovalsetting',
            name='select_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settlementapprovalsetting',
            name='select_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expenseapprovalsetting',
            name='employee',
            field=models.ManyToManyField(related_name='expense_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenseapprovalsetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_setting', to='organization.Organization'),
        ),
    ]
