# Generated by Django 3.2.12 on 2022-09-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0008_auto_20220824_1506'),
        ('reimbursement', '0008_merge_20220729_1114'),
    ]

    operations = [
    ]
