# Generated by Django 3.2.12 on 2023-03-17 06:48

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reimbursement', '0010_reimbursementsetting_travel_report_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequestFromAdvanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateField()),
                ('start_time', models.TimeField()),
                ('end', models.DateField()),
                ('end_time', models.TimeField()),
                ('advance_expense_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel_request_from_advance', to='reimbursement.advanceexpenserequest')),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_travelrequestfromadvancerequest_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_travelrequestfromadvancerequest_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
