# Generated by Django 3.2.12 on 2023-05-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0011_travelrequestfromadvancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceexpenserequest',
            name='requested_amount',
            field=models.FloatField(default=0),
        ),
    ]
