# Generated by Django 3.2.12 on 2023-12-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0012_advanceexpenserequest_requested_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanceexpenserequesthistory',
            name='target',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settlementhistory',
            name='target',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
