# Generated by Django 3.2.12 on 2024-02-21 03:23

import cuser.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reimbursement', '0013_auto_20231221_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceExpenseCancelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied')], db_index=True, default='Requested', max_length=20)),
                ('remarks', models.CharField(max_length=255)),
                ('advance_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_history', to='reimbursement.advanceexpenserequest')),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpensecancelhistory_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpensecancelhistory_modified', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ManyToManyField(related_name='cancel_request_to_act', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvanceExpenseCancelRequestApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], db_index=True, max_length=25)),
                ('role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], db_index=True, max_length=25)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('remarks', models.TextField(max_length=600)),
                ('add_signature', models.BooleanField(default=False)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancel_actors', to=settings.AUTH_USER_MODEL)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpensecancelrequestapproval_created', to=settings.AUTH_USER_MODEL)),
                ('expense_cancel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='reimbursement.advanceexpensecancelhistory')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_advanceexpensecancelrequestapproval_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='cancel_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('level',),
            },
        ),
    ]
