# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('task', '0001_initial'),
        ('organization', '0002_auto_20210211_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userresultarea',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_userresultarea_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresultarea',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_userresultarea_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresultarea',
            name='result_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_users', to='task.ResultArea'),
        ),
        migrations.AddField(
            model_name='userresultarea',
            name='user_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_result_areas', to='users.UserExperience'),
        ),
        migrations.AddField(
            model_name='taskverificationscore',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.TaskAssociation'),
        ),
        migrations.AddField(
            model_name='taskverificationscore',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskverificationscore_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskverificationscore',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskverificationscore_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskreminder_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskreminder_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_task_reminder', to='task.Task'),
        ),
        migrations.AddField(
            model_name='taskreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskproject',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskproject_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskproject',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Project Members'),
        ),
        migrations.AddField(
            model_name='taskproject',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskproject_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskcomment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskcomment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='task.Task'),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskchecklist_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskchecklist_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_checklists', to='task.Task'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskattachment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskattachment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='task.Task'),
        ),
        migrations.AddField(
            model_name='taskassociation',
            name='core_tasks',
            field=models.ManyToManyField(to='task.CoreTask'),
        ),
        migrations.AddField(
            model_name='taskassociation',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskassociation_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassociation',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskassociation_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassociation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_associations', to='task.Task'),
        ),
        migrations.AddField(
            model_name='taskassociation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskactivity_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_taskactivity_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskactivity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='task.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_task_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_task_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='task.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='task.TaskProject'),
        ),
        migrations.AddField(
            model_name='resultarea',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_resultarea_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resultarea',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division_result_areas', to='organization.OrganizationDivision'),
        ),
        migrations.AddField(
            model_name='resultarea',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_resultarea_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtaskdate',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_recurringtaskdate_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtaskdate',
            name='created_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AddField(
            model_name='recurringtaskdate',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_recurringtaskdate_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtaskdate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_task_queue', to='task.Task'),
        ),
        migrations.AddField(
            model_name='coretask',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_coretask_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coretask',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_coretask_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coretask',
            name='result_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_tasks', to='task.ResultArea'),
        ),
        migrations.AlterUniqueTogether(
            name='userresultarea',
            unique_together={('user_experience', 'result_area')},
        ),
        migrations.AlterUniqueTogether(
            name='taskassociation',
            unique_together={('user', 'task')},
        ),
        migrations.AlterUniqueTogether(
            name='resultarea',
            unique_together={('title', 'division')},
        ),
        migrations.AlterUniqueTogether(
            name='coretask',
            unique_together={('result_area', 'order')},
        ),
    ]
