# Generated by Django 2.2.11 on 2021-06-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_activity_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='client_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
