# Generated by Django 2.2.11 on 2021-06-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_activity_client_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='employee_rate',
            field=models.FloatField(default=0),
        ),
    ]
