# Generated by Django 2.2.11 on 2021-06-24 02:52

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0007_auto_20210621_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('unit', models.FloatField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('activity_description', models.CharField(max_length=600, unique=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='task.Activity')),
                ('core_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='task.CoreTask')),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_worklog_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_worklog_modified', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='task.Project')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='task.Task')),
            ],
            options={
                'unique_together': {('project', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='WorkLogAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('attachment_name', models.CharField(max_length=150)),
                ('attachment', models.FileField(upload_to='')),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_worklogattachment_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_worklogattachment_modified', to=settings.AUTH_USER_MODEL)),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_attachments', to='task.WorkLog')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkLogAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('draft', 'draft'), ('requested', 'requested'), ('approved', 'approved'), ('denied', 'denied'), ('forwarded', 'forwarded'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('acknowledge', 'acknowledge')], max_length=20)),
                ('remarks', models.CharField(max_length=600)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_worklogaction_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_worklogaction_modified', to=settings.AUTH_USER_MODEL)),
                ('worklog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_actions', to='task.WorkLog')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
