# Generated by Django 2.2.11 on 2021-06-24 11:03

from django.conf import settings
from django.db import migrations, models
import irhrs.task.models.worklog


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0008_worklog_worklogaction_worklogattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogaction',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, validators=[irhrs.task.models.worklog.validate_score]),
        ),
        migrations.AlterField(
            model_name='worklogaction',
            name='action',
            field=models.CharField(choices=[('todo', 'todo'), ('draft', 'draft'), ('requested', 'requested'), ('approved', 'approved'), ('denied', 'denied'), ('forwarded', 'forwarded'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('acknowledge', 'acknowledge')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='worklog',
            unique_together={('project', 'activity', 'created_by')},
        ),
    ]
