# Generated by Django 2.2.11 on 2021-06-24 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='client_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='employee_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='unit',
            field=models.CharField(choices=[('hour', 'hour'), ('piece', 'piece'), ('day', 'day')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
