# Generated by Django 2.2.11 on 2021-06-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20210624_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
