# Generated by Django 2.2.11 on 2021-06-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20210625_1336'),
        ('task', '0009_auto_20210624_1648'),
    ]

    operations = [
    ]
