# Generated by Django 2.2.11 on 2021-06-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_merge_20210628_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='worklogaction',
            name='action',
            field=models.CharField(choices=[('todo', 'todo'), ('draft', 'draft'), ('requested', 'requested'), ('approved', 'approved'), ('denied', 'denied'), ('forwarded', 'forwarded'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('acknowledged', 'acknowledged')], max_length=20),
        ),
        migrations.DeleteModel(
            name='WorkLogAttachment',
        ),
    ]
