# Generated by Django 2.2.11 on 2021-06-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20210629_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worklog',
            options={'ordering': ('-created_at', '-modified_at')},
        ),
        migrations.AlterUniqueTogether(
            name='worklog',
            unique_together=set(),
        ),
    ]
