# Generated by Django 2.2.11 on 2021-06-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20210630_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklogaction',
            name='remarks',
            field=models.TextField(max_length=600),
        ),
    ]
