# Generated by Django 2.2.11 on 2021-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_auto_20210630_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklogaction',
            name='remarks',
            field=models.TextField(),
        ),
    ]
