# Generated by Django 2.2.11 on 2021-07-01 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0016_auto_20210630_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worklogaction',
            name='action_performed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_worklogs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worklogaction',
            name='action_performed_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_worklogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='activity_description',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
