# Generated by Django 2.2.11 on 2021-07-02 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0017_auto_20210701_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='user',
        ),
        migrations.AddField(
            model_name='worklog',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worklog',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='activity_description',
            field=models.CharField(max_length=255),
        ),
    ]
