# Generated by Django 2.2.11 on 2021-07-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_auto_20210705_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklogaction',
            name='action_performed_to',
        ),
    ]
