# Generated by Django 2.2.11 on 2021-07-09 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_remove_worklogaction_action_performed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='total_amount',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='worklogaction',
            name='action_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklogaction',
            name='action',
            field=models.CharField(choices=[('todo', 'todo'), ('draft', 'draft'), ('requested', 'requested'), ('approved', 'approved'), ('denied', 'denied'), ('forwarded', 'forwarded'), ('confirmed', 'confirmed'), ('canceled', 'canceled'), ('acknowledged', 'acknowledged'), ('sent', 'sent')], max_length=20),
        ),
    ]
