# Generated by Django 2.2.11 on 2021-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_auto_20210712_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='core_task',
            field=models.ManyToManyField(blank=True, related_name='daily_tasks', to='task.CoreTask'),
        ),
    ]
