# Generated by Django 2.2.11 on 2021-07-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_auto_20210712_1755'),
    ]

    operations = [
        migrations.RunSQL(
            'drop index if exists "task_taskassociation_cycle_status_2e829596";'
        ),
        migrations.RunSQL(
            'drop index if exists "task_taskassociation_cycle_status_2e829596_like";'
        ),
        migrations.AlterField(
            model_name='taskassociation',
            name='cycle_status',
            field=models.CharField(blank=True, choices=[('Approval Pending', 'Approval Pending'), ('Score Not Provided', 'Score Not Provided'), ('Acknowledge Pending', 'Acknowledge Pending'), ('Forwarded To HR', 'Forwarded To HR'), ('Approved By HR', 'Approved By HR'), ('Acknowledged', 'Acknowledged'), ('Not Acknowledged', 'Not Acknowledged')], db_index=True, default='Approval Pending', max_length=32),
        ),
    ]
