# Generated by Django 2.2.11 on 2021-11-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_auto_20210719_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='activity_description',
            field=models.CharField(max_length=600),
        ),
    ]
