# Generated by Django 3.2.12 on 2022-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_auto_20211102_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskverificationscore',
            name='ack',
            field=models.BooleanField(null=True),
        ),
    ]
