# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrelatedfieldsinfo',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_reportrelatedfieldsinfo_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportrelatedfieldsinfo',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_reportrelatedfieldsinfo_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportrelatedfieldsinfo',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportrelatedfieldsinfo', to='builder.Report'),
        ),
        migrations.AddField(
            model_name='reportfilterfield',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_reportfilterfield_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfilterfield',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_reportfilterfield_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfilterfield',
            name='report_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportfilterfield', to='builder.ReportFilter'),
        ),
        migrations.AddField(
            model_name='reportfilter',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_reportfilter_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfilter',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_reportfilter_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportfilter',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reportfilter', to='builder.Report'),
        ),
        migrations.AddField(
            model_name='reportdisplayfield',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_reportdisplayfield_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdisplayfield',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_reportdisplayfield_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportdisplayfield',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportdisplayfield', to='builder.Report'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_report_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_report_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
