# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20210430_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdisplayfield',
            name='ordering',
            field=models.CharField(blank=True, choices=[('Asc', 'Ascending'), ('Desc', 'Descending')], db_index=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='reportfilterfield',
            name='filter_type',
            field=models.CharField(choices=[('exact', 'Equals'), ('iexact', 'Equals (case-insensitive)'), ('contains', 'Contains'), ('icontains', 'Contains (case-insensitive)'), ('in', 'in (comma separated 1,2,3)'), ('gt', 'Greater than'), ('gte', 'Greater than equals'), ('lt', 'Less than'), ('lte', 'Less than equals'), ('startswith', 'Starts with'), ('istartswith', 'Starts with (case-insensitive)'), ('endswith', 'Ends with'), ('iendswith', 'Ends with  (case-insensitive)'), ('range', 'range'), ('isnull', 'Is null')], db_index=True, default='exact', max_length=15),
        ),
    ]
