# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        ('organization', '0002_auto_20210211_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrainingrequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_usertrainingrequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertrainingrequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_usertrainingrequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertrainingrequest',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to='training.Training'),
        ),
        migrations.AddField(
            model_name='usertrainingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_usertraining_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_usertraining_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='training',
            field=models.ForeignKey(help_text='The training user wishes to join', on_delete=django.db.models.deletion.CASCADE, related_name='user_trainings', to='training.Training'),
        ),
        migrations.AddField(
            model_name='usertraining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainingtype_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainingtype_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainingfeedback_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainingfeedback_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='training.Training'),
        ),
        migrations.AddField(
            model_name='trainingfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainingattendance_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='external_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_attendance', to='training.Trainer'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainingattendance_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendance', to='training.Training'),
        ),
        migrations.AddField(
            model_name='trainingattachments',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainingattachments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattachments',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainingattachments_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingattachments',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='training.Training'),
        ),
        migrations.AddField(
            model_name='trainingattachment',
            name='training_attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='training.TrainingAttachments'),
        ),
        migrations.AddField(
            model_name='training',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_training_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='external_trainers',
            field=models.ManyToManyField(related_name='external_trainers', to='training.Trainer'),
        ),
        migrations.AddField(
            model_name='training',
            name='internal_trainers',
            field=models.ManyToManyField(related_name='internal_trainers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_training_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(help_text='The Type of this training. The budget and budget hours are subset to this FK.', on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='training.TrainingType'),
        ),
        migrations.AddField(
            model_name='trainerattachments',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainerattachments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerattachments',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainerattachments_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerattachments',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='training.Trainer'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainer',
            name='expertise',
            field=models.ManyToManyField(to='organization.KnowledgeSkillAbility'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_trainer_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='recurringtrainingdate',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_recurringtrainingdate_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtrainingdate',
            name='created_training',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.Training'),
        ),
        migrations.AddField(
            model_name='recurringtrainingdate',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_recurringtrainingdate_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringtrainingdate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_training_queue', to='training.Training'),
        ),
    ]
