# Generated by Django 2.2.11 on 2021-04-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210211_1614'),
        ('training', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='meeting_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training', to='organization.MeetingRoomStatus'),
        ),
    ]
