# Generated by Django 2.2.11 on 2021-05-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_training_meeting_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='location',
            field=models.TextField(help_text='Where will the training be held?', null=True),
        ),
    ]
