# Generated by Django 2.2.11 on 2021-05-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210211_1614'),
        ('training', '0004_auto_20210503_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='branch',
            field=models.ManyToManyField(blank=True, related_name='training_branch', to='organization.OrganizationBranch'),
        ),
        migrations.AddField(
            model_name='training',
            name='division',
            field=models.ManyToManyField(blank=True, related_name='training_division', to='organization.OrganizationDivision'),
        ),
        migrations.AddField(
            model_name='training',
            name='employment_level',
            field=models.ManyToManyField(blank=True, related_name='training_employment_level', to='organization.EmploymentLevel'),
        ),
        migrations.AddField(
            model_name='training',
            name='employment_type',
            field=models.ManyToManyField(blank=True, related_name='training_employment_type', to='organization.EmploymentStatus'),
        ),
        migrations.AddField(
            model_name='training',
            name='job_title',
            field=models.ManyToManyField(blank=True, related_name='training_job_title', to='organization.EmploymentJobTitle'),
        ),
    ]
