# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20210505_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Training Status: Pending, Completed, In Progress, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='usertrainingrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, max_length=10),
        ),
    ]
