# Generated by Django 3.2.12 on 2022-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210629_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertraining',
            name='training_need',
            field=models.CharField(choices=[('request', 'User Requested'), ('assessment', 'Assessment'), ('performance-appraisal', 'Performance Appraisal'), ('task-efficiency', 'Task Efficiency'), ('others', 'Others')], help_text='\n            Why the user needs this training?\n            1. User Could have asked for training\n            2. An assessment report concluded this necessity.\n            3. Through Performance Appraisal.\n        ', max_length=21),
        ),
    ]
