# Generated by Django 2.2.11 on 2021-07-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20210629_1553'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestionset',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_question_sets', to='organization.Organization'),
            preserve_default=False,
        ),
    ]
