# Generated by Django 2.2.11 on 2021-07-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formquestionset_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformanswersheet',
            name='next_approval_level',
            field=models.FloatField(null=True),
        ),
    ]
