# Generated by Django 2.2.11 on 2021-07-28 02:42

import cuser.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0004_userformindividualquestionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformanswersheet',
            name='question_answers',
            field=models.ManyToManyField(to='forms.UserFormIndividualQuestionAnswer'),
        ),
        migrations.RemoveField(
            model_name='userformindividualquestionanswer',
            name='answers',
        ),
        migrations.AddField(
            model_name='userformindividualquestionanswer',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AnonymousFormIndividualQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_individual_question_answers', to='forms.AnonymousFormAnswerSheet')),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms_anonymousformindividualquestionanswer_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms_anonymousformindividualquestionanswer_modified', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_individual_question_answers', to='forms.FormQuestion')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='anonymousformanswersheet',
            name='question_answers',
            field=models.ManyToManyField(to='forms.AnonymousFormIndividualQuestionAnswer'),
        ),
    ]
