# Generated by Django 2.2.11 on 2021-08-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20210728_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousformanswersheet',
            name='question_answer',
        ),
        migrations.RemoveField(
            model_name='userformanswersheet',
            name='question_answer',
        ),
    ]
