# Generated by Django 2.2.11 on 2021-09-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_auto_20210803_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='formquestion',
            name='answer_visible_to_all_users',
            field=models.BooleanField(default=False),
        ),
    ]
