# Generated by Django 3.2.12 on 2022-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_formquestion_answer_visible_to_all_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousformindividualquestionanswer',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userformindividualquestionanswer',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
