# Generated by Django 2.2.11 on 2021-02-11 10:29

import django.core.validators
from django.db import migrations, models
import irhrs.core.utils.common
import irhrs.core.validators
import irhrs.event.utils.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the Event', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the Event', max_length=100000, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('event_type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=8)),
                ('event_category', models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Meeting', 'Meeting'), ('Conference', 'Conference'), ('Interview', 'Interview'), ('Refreshment', 'Refreshment'), ('Recreation', 'Recreation'), ('Training', 'Training'), ('Panel Discussion', 'Panel Discussion'), ('Group Discussion', 'Group Discussion'), ('Celebration', 'Celebration'), ('Development Programs', 'Development Programs'), ('Others', 'Others')], default='Others', max_length=20)),
                ('start_at', models.DateTimeField(validators=[irhrs.core.validators.validate_future_datetime])),
                ('end_at', models.DateTimeField(validators=[irhrs.core.validators.validate_future_datetime])),
                ('_featured_image', models.ImageField(blank=True, db_column='featured_image', null=True, upload_to=irhrs.event.utils.util.get_event_featured_image)),
                ('members_can_modify', models.BooleanField(db_column='m_can_modify', default=False, help_text='If set members can modify event')),
                ('members_can_invite', models.BooleanField(db_column='m_can_invite', default=False, help_text='If set members can invite other members to join event')),
                ('members_can_see_guest', models.BooleanField(db_column='m_can_see_guest', default=False, help_text='If set members can see guest list')),
                ('repeat_rule', models.CharField(blank=True, max_length=100, null=True)),
                ('interactive_event', models.BooleanField(default=False, help_text='If set members of this event can post and comment')),
                ('enabled_event', models.BooleanField(default=True)),
                ('event_location', models.CharField(choices=[('Inside', 'Inside'), ('Outside', 'Outside')], default='Inside', max_length=8)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('invitation_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Maybe', 'Maybe')], default='Pending', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('other_information', models.TextField(blank=True, max_length=100000, null=True)),
                ('prepared', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingAcknowledgeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=2000)),
                ('discussion', models.TextField(blank=True, max_length=100000, null=True)),
                ('decision', models.TextField(blank=True, max_length=100000, null=True)),
                ('discussed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('Meeting Organizer', 'Meeting Organizer'), ('Time Keeper / Minuter', 'Time Keeper / Minuter'), ('Time Keeper', 'Time Keeper'), ('Minuter', 'Minuter'), ('Member', 'Member')], default='Member', max_length=22)),
                ('arrival_time', models.DateTimeField(null=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to=irhrs.core.utils.common.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'odt', 'pdf', 'xls', 'xlsx', 'ods', 'ppt', 'pptx', 'txt', 'tif', 'tiff', 'jif', 'jfif', 'jp2', 'jpx', 'j2k', 'j2c', 'fpx', 'pcd', 'psd', 'rtf', 'gif', 'jpeg', 'jpg', 'png'])])),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('notified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
