# Generated by Django 2.2.11 on 2021-04-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meeting',
            new_name='EventDetail',
        ),
        migrations.RunSQL(
            'alter sequence event_meeting_id_seq rename to event_eventdetail_id_seq;'),
    ]
