# Generated by Django 2.2.11 on 2021-04-21 12:25

import cuser.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210421_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_eventdetail_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_eventdetail_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
