# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210421_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('Seminar', 'Seminar'), ('Workshop', 'Workshop'), ('Meeting', 'Meeting'), ('Conference', 'Conference'), ('Interview', 'Interview'), ('Refreshment', 'Refreshment'), ('Recreation', 'Recreation'), ('Training', 'Training'), ('Panel Discussion', 'Panel Discussion'), ('Group Discussion', 'Group Discussion'), ('Celebration', 'Celebration'), ('Development Programs', 'Development Programs'), ('Others', 'Others')], db_index=True, default='Others', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_location',
            field=models.CharField(choices=[('Inside', 'Inside'), ('Outside', 'Outside')], db_index=True, default='Inside', max_length=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], db_index=True, default='Public', max_length=8),
        ),
        migrations.AlterField(
            model_name='eventmembers',
            name='invitation_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Maybe', 'Maybe')], db_index=True, default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='position',
            field=models.CharField(choices=[('Meeting Organizer', 'Meeting Organizer'), ('Time Keeper / Minuter', 'Time Keeper / Minuter'), ('Time Keeper', 'Time Keeper'), ('Minuter', 'Minuter'), ('Member', 'Member')], db_index=True, default='Member', max_length=22),
        ),
    ]
