# Generated by Django 2.2.11 on 2021-02-11 10:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import irhrs.core.fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_interactive', models.BooleanField(default=False)),
                ('interactive_type', models.CharField(choices=[('leave_request', 'leave_request'), ('leave_cancel_request', 'leave_cancel_request'), ('adjustment_request', 'adjustment_request'), ('overtime_claim', 'overtime_claim'), ('task_approval', 'task_approval'), ('task_acknowledge', 'task_acknowledge'), ('travel_attendance', 'travel_attendance'), ('travel_attendance_delete', 'travel_attendance_delete'), ('overtime_pre_approval', 'overtime_pre_approval'), ('credit_hour_pre_approval', 'credit_hour_pre_approval'), ('credit_hour_pre_approval_delete', 'credit_hour_pre_approval_delete'), ('web_attendance', 'web_attendance'), ('timesheet_report', 'timesheet_report')], max_length=50, null=True)),
                ('interactive_data', irhrs.core.fields.fields.JSONTextField(null=True)),
                ('text', models.TextField(blank=True)),
                ('action_object_id', models.PositiveIntegerField()),
                ('url', models.TextField(blank=True, null=True)),
                ('label', models.CharField(choices=[('Warning', 'Warning'), ('Danger', 'Danger'), ('Info', 'Info'), ('Success', 'Success')], default='Info', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('notify_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('sticky', models.BooleanField(default=False)),
                ('can_be_reminded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-notify_on',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_interactive', models.BooleanField(default=False)),
                ('interactive_type', models.CharField(choices=[('leave_request', 'leave_request'), ('leave_cancel_request', 'leave_cancel_request'), ('adjustment_request', 'adjustment_request'), ('overtime_claim', 'overtime_claim'), ('task_approval', 'task_approval'), ('task_acknowledge', 'task_acknowledge'), ('travel_attendance', 'travel_attendance'), ('travel_attendance_delete', 'travel_attendance_delete'), ('overtime_pre_approval', 'overtime_pre_approval'), ('credit_hour_pre_approval', 'credit_hour_pre_approval'), ('credit_hour_pre_approval_delete', 'credit_hour_pre_approval_delete'), ('web_attendance', 'web_attendance'), ('timesheet_report', 'timesheet_report')], max_length=50, null=True)),
                ('interactive_data', irhrs.core.fields.fields.JSONTextField(null=True)),
                ('text', models.TextField(blank=True)),
                ('url', models.TextField(blank=True)),
                ('action_object_id', models.PositiveIntegerField()),
                ('label', models.CharField(choices=[('Warning', 'Warning'), ('Danger', 'Danger'), ('Info', 'Info'), ('Success', 'Success')], default='Info', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('notify_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_group_notifications', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-notify_on',),
            },
        ),
    ]
