# Generated by Django 2.2.11 on 2021-06-28 08:18

import json
import os

import django.contrib.postgres.fields
from django.contrib.postgres.fields.array import ArrayField
from django.db import migrations, models


def do_nothing(*args, **kwargs):
    ...


def dump_permission_codes(apps, schema_editor):
    OrganizationNotification = apps.get_model(
        "notification", "OrganizationNotification")

    notification_code_map = OrganizationNotification.objects.values_list(
        'id', 'associated_permissions__code')

    _PERM_CODE_MAP = {}

    def update_or_create(_id, _code):
        if _code is None:
            return
        if _id in _PERM_CODE_MAP:
            res = _PERM_CODE_MAP[_id]
            res.append(_code)
        else:
            _PERM_CODE_MAP[_id] = [_code]
    for notification_id, permission_code in notification_code_map:
        update_or_create(notification_id, permission_code)

    with open('permission_codes.json', 'w') as json_file:
        json.dump(_PERM_CODE_MAP, json_file)


def load_permission_to_array_field(apps, schema_editor):
    OrganizationNotification = apps.get_model(
        "notification", "OrganizationNotification")

    with open('permission_codes.json', 'r') as json_file:
        _PERM_CODE_MAP = json.load(json_file)

    for _id, _codes in _PERM_CODE_MAP.items():
        OrganizationNotification.objects.filter(id=_id).update(
            associated_permissions=_codes)

    try:
        os.remove('permission_codes.json')
    except OSError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.RunPython(
            dump_permission_codes,
            reverse_code=do_nothing
        ),
        migrations.RemoveField(
            model_name='organizationnotification',
            name='associated_permissions',
        ),
        migrations.AddField(
            model_name='organizationnotification',
            name='associated_permissions',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.RunPython(
            load_permission_to_array_field,
            reverse_code=do_nothing
        )
    ]
