# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20210628_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='interactive_type',
            field=models.CharField(choices=[('leave_request', 'leave_request'), ('leave_cancel_request', 'leave_cancel_request'), ('adjustment_request', 'adjustment_request'), ('overtime_claim', 'overtime_claim'), ('task_approval', 'task_approval'), ('task_acknowledge', 'task_acknowledge'), ('travel_attendance', 'travel_attendance'), ('travel_attendance_delete', 'travel_attendance_delete'), ('overtime_pre_approval', 'overtime_pre_approval'), ('credit_hour_pre_approval', 'credit_hour_pre_approval'), ('credit_hour_pre_approval_delete', 'credit_hour_pre_approval_delete'), ('web_attendance', 'web_attendance'), ('timesheet_report', 'timesheet_report')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='label',
            field=models.CharField(choices=[('Warning', 'Warning'), ('Danger', 'Danger'), ('Info', 'Info'), ('Success', 'Success')], db_index=True, default='Info', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationnotification',
            name='interactive_type',
            field=models.CharField(choices=[('leave_request', 'leave_request'), ('leave_cancel_request', 'leave_cancel_request'), ('adjustment_request', 'adjustment_request'), ('overtime_claim', 'overtime_claim'), ('task_approval', 'task_approval'), ('task_acknowledge', 'task_acknowledge'), ('travel_attendance', 'travel_attendance'), ('travel_attendance_delete', 'travel_attendance_delete'), ('overtime_pre_approval', 'overtime_pre_approval'), ('credit_hour_pre_approval', 'credit_hour_pre_approval'), ('credit_hour_pre_approval_delete', 'credit_hour_pre_approval_delete'), ('web_attendance', 'web_attendance'), ('timesheet_report', 'timesheet_report')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organizationnotification',
            name='label',
            field=models.CharField(choices=[('Warning', 'Warning'), ('Danger', 'Danger'), ('Info', 'Info'), ('Success', 'Success')], db_index=True, default='Info', max_length=20),
        ),
    ]
