# Generated by Django 2.2.11 on 2021-03-16 08:21

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontactdetail',
            name='address',
            field=models.CharField(max_length=255, validators=[irhrs.core.validators.validate_address]),
        ),
        migrations.AlterField(
            model_name='usercontactdetail',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='usercontactdetail',
            name='number_type',
            field=models.CharField(blank=True, choices=[('Fax', 'Fax'), ('Phone', 'Phone'), ('Mobile', 'Mobile'), ('Work', 'Work')], db_index=True, max_length=10),
        ),
    ]
