# Generated by Django 2.2.11 on 2021-06-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210604_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailunsubscribe',
            name='email_type',
            field=models.PositiveIntegerField(choices=[(1, 'Birthday Email'), (2, 'Anniversary Email'), (3, 'Holiday Email'), (4, 'When you are invited to an event/meeting'), (5, 'When an event/meeting, you are involved, is updated'), (6, 'When an event/meeting, you are involved, is cancelled'), (40, 'When an assessment is assigned to a user.'), (41, 'When an user completes an assigned assessment(For HR Only)')]),
        ),
    ]
