# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210623_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], db_index=True, default='Single', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='policy_type',
            field=models.CharField(choices=[('health_insurance', 'Health Insurance'), ('life_insurance', 'Life Insurance')], db_index=True, default='health_insurance', max_length=20),
        ),
    ]
