# Generated by Django 2.2.11 on 2021-08-11 07:12

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210629_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='completeness_percent',
            field=models.PositiveIntegerField(default=0, validators=[irhrs.core.validators.MinMaxValueValidator(0, 100)]),
        ),
    ]
