# Generated by Django 2.2.11 on 2021-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userdetail_completeness_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremailunsubscribe',
            name='email_type',
            field=models.PositiveIntegerField(choices=[(1, 'Birthday Email'), (2, 'Anniversary Email'), (3, 'Holiday Email'), (4, 'When you are invited to an event/meeting'), (5, 'When an event/meeting, you are involved, is updated'), (6, 'When an event/meeting, you are involved, is cancelled'), (40, 'When an assessment is assigned/unassigned to a user.'), (41, 'When an user completes an assigned assessment(For HR Only)'), (42, "When an employee's expiry date is in critical date range(For HR only)."), (43, 'When a training is assigned/unassigned.'), (44, 'When a training is deleted/cancelled.'), (45, 'When a training is requested by user(For HR only).'), (47, 'When a training request is acted upon.'), (46, 'When a training is updated.'), (48, 'When a user sends a resignation request.'), (49, 'When HR takes an action on resignation request.'), (50, 'When HR does not take action on resignation request for a certain interval(For HR only).'), (51, 'When User request for Advance expenses '), (52, 'When User Settles on advance request'), (53, 'When Request is Approved and denieed for request of advance salary and expenses')]),
        ),
    ]
