# Generated by Django 2.2.11 on 2022-01-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220114_2320'),
        ('users', '0017_auto_20220106_1438'),
    ]

    operations = [
    ]
