# Generated by Django 2.2.11 on 2022-02-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20220127_1020'),
        ('users', '0018_auto_20220120_1358'),
    ]

    operations = [
    ]
