# Generated by Django 2.2.11 on 2022-02-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20220203_1513'),
        ('users', '0019_merge_20220203_1212'),
    ]

    operations = [
    ]
