# Generated by Django 2.2.11 on 2022-03-31 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220208_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinsurance',
            name='annual_premium',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='insured_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userinsurance',
            name='insured_scheme',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
