# Generated by Django 2.2.11 on 2022-03-31 11:17

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20220208_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactdetail',
            name='dependent_id_number',
            field=models.CharField(default='', max_length=50, validators=[irhrs.core.validators.validate_invalid_chars, irhrs.core.validators.validate_has_digit]),
        ),
        migrations.AddField(
            model_name='usercontactdetail',
            name='dependent_id_type',
            field=models.IntegerField(choices=[(1, 'citizenship certificate'), (2, 'birth certificate')], null=True),
        ),
        migrations.AddField(
            model_name='usercontactdetail',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usercontactdetail',
            name='contact_of',
            field=models.CharField(choices=[('Self', 'Self'), ('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Sibling', 'Sibling'), ('Friend', 'Friend'), ('Relative', 'Relative'), ('Home', 'Home'), ('Office', 'Office'), ('Family', 'Family'), ('Parent', 'Parent'), ('Children', 'Children')], default='Self', max_length=15),
        ),
    ]
