# Generated by Django 2.2.11 on 2022-03-31 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20220331_1702'),
        ('users', '0022_auto_20220331_1454'),
    ]

    operations = [
    ]
