# Generated by Django 2.2.11 on 2022-04-07 10:49

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_merge_20220331_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlegalinfo',
            name='citizenship_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlegalinfo',
            name='citizenship_issue_place',
            field=models.CharField(blank=True, max_length=255, validators=[irhrs.core.validators.validate_invalid_chars]),
        ),
        migrations.AddField(
            model_name='userlegalinfo',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlegalinfo',
            name='passport_issue_place',
            field=models.CharField(blank=True, max_length=255, validators=[irhrs.core.validators.validate_invalid_chars]),
        ),
    ]
