# Generated by Django 2.2.11 on 2022-04-07 10:35
import json
import os

from django.db import migrations, models
import django.db.models.deletion

from config import settings


def update_province_name(apps, schema_editor):
    Country = apps.get_model(
        "recruitment", "Country")
    Province = apps.get_model(
        "recruitment", "Province")
    District = apps.get_model(
        "recruitment", "District")

    with open(
        os.path.abspath(
            os.path.join(
                settings.PROJECT_DIR,
                'fixtures/commons/locations.json'
            )
        )
    ) as f:
        location_data = json.load(f)
        countries = location_data['countries']
        provinces = location_data['provinces']
        districts = location_data['districts']

    # seed country
    for country_data in countries:
        _id = country_data.pop('id')
        Country.objects.get_or_create(id=_id, defaults=country_data)

    # seed province
    for province in provinces:
        _id = province.pop('id')
        nepal = Country.objects.get(name="Nepal")
        province.update({"country": nepal})
        Province.objects.update_or_create(id=_id, defaults=province)

    for district in districts:
        _id = district["id"]

        data = {
            "province_id": district["province_id"],
            "name": district["name"].title(),
            "alternative_names": district.get("alternative_names", []),
            "alternative_names_ne": district.get("alternative_names_ne", [])
        }
        District.objects.get_or_create(id=_id, defaults=data)


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_location_country_ref'),
        ('users', '0023_merge_20220331_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='country_ref',
            field=models.ForeignKey(blank=True, default=603, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recruitment.Country'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recruitment.District'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recruitment.Province'),
        ),
        migrations.RunPython(update_province_name)
    ]
