# Generated by Django 2.2.11 on 2022-04-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20220407_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlegalinfo',
            name='citizenship_issue_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userlegalinfo',
            name='passport_issue_place',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
