# Generated by Django 2.2.11 on 2022-04-12 06:28

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220412_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlegalinfo',
            name='citizenship_issue_date',
            field=models.DateField(blank=True, null=True, validators=[irhrs.core.validators.validate_past_date_or_today]),
        ),
        migrations.AlterField(
            model_name='userlegalinfo',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, validators=[irhrs.core.validators.validate_past_date_or_today]),
        ),
    ]
