# Generated by Django 2.2.11 on 2022-04-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20220407_1620'),
        ('users', '0026_auto_20220412_1213'),
    ]

    operations = [
    ]
