# Generated by Django 2.2.11 on 2022-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_merge_20220419_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
