# Generated by Django 3.2.12 on 2022-05-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_changerequest_is_deleted'),
        ('users', '0028_useraddress_postal_code'),
    ]

    operations = [
    ]
