# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('HR Notice', 'HR Notice'), ('Division Notice', 'Division Notice'), ('Normal Post', 'Normal Post'), ('Auto Generated', 'Auto Generated'), ('Organization Notice', 'Organization Notice')], db_index=True, default='Normal Post', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], db_index=True, default='Approved', max_length=50),
        ),
    ]
