# Generated by Django 3.2.12 on 2022-10-20 11:59

import django.core.validators
from django.db import migrations, models
import irhrs.core.utils.common


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_auto_20210629_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(null=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'odt', 'pdf', 'xls', 'xlsx', 'ods', 'ppt', 'pptx', 'txt', 'tif', 'tiff', 'jif', 'jfif', 'jp2', 'jpx', 'j2k', 'j2c', 'fpx', 'pcd', 'psd', 'rtf', 'gif', 'jpeg', 'jpg', 'png'])]),
        ),
    ]
