# Generated by Django 3.2.12 on 2022-10-20 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_post_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attachment',
            new_name='upload_file',
        ),
    ]
