# Generated by Django 3.2.12 on 2023-10-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_rename_attachment_post_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Condolence Post', 'Condolence Post'), ('HR Notice', 'HR Notice'), ('Division Notice', 'Division Notice'), ('Normal Post', 'Normal Post'), ('Auto Generated', 'Auto Generated'), ('Organization Notice', 'Organization Notice')], db_index=True, default='Normal Post', max_length=50),
        ),
    ]
