# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('leave', '0001_initial'),
        ('attendance', '0002_auto_20210211_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yearsofservicerule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_yearsofservicerule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yearsofservicerule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_yearsofservicerule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yearsofservicerule',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yos_rule', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='timeoffrule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_timeoffrule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeoffrule',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.LeaveType'),
        ),
        migrations.AddField(
            model_name='timeoffrule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_timeoffrule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeoffrule',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_rule', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='renewalrule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_renewalrule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renewalrule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_renewalrule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renewalrule',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_rule', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='mastersetting',
            name='cloned_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_settings', to='leave.MasterSetting'),
        ),
        migrations.AddField(
            model_name='mastersetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_mastersetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mastersetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_mastersetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mastersetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_master_settings', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='cloned_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_leave_types', to='leave.LeaveType'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leavetype_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='master_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='leave.MasterSetting'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leavetype_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavesheet',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leavesheet_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavesheet',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leavesheet_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavesheet',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='leave.LeaveRequest'),
        ),
        migrations.AddField(
            model_name='leaverule',
            name='cloned_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_leave_rules', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='leaverule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverule',
            name='depletion_leave_types',
            field=models.ManyToManyField(related_name='need_depletion', to='leave.LeaveType'),
        ),
        migrations.AddField(
            model_name='leaverule',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_rules', to='leave.LeaveType'),
        ),
        migrations.AddField(
            model_name='leaverule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequesthistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequesthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverequesthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequesthistory',
            name='forwarded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequesthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverequesthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequesthistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leave.LeaveRequest'),
        ),
        migrations.AddField(
            model_name='leaverequestdeletestatushistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverequestdeletestatushistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequestdeletestatushistory',
            name='delete_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='leave.LeaveRequestDeleteHistory'),
        ),
        migrations.AddField(
            model_name='leaverequestdeletestatushistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverequestdeletestatushistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequestdeletehistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverequestdeletehistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequestdeletehistory',
            name='leave_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_history', to='leave.LeaveRequest'),
        ),
        migrations.AddField(
            model_name='leaverequestdeletehistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverequestdeletehistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequestdeletehistory',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverequest_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave.LeaveAccount'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaverequest_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveirregularitiesrule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveirregularitiesrule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveirregularitiesrule',
            name='leave_rule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_irregularity', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='leaveirregularitiesrule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveirregularitiesrule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveencashmenthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveencashmenthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveencashmenthistory',
            name='encashment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leave.LeaveEncashment'),
        ),
        migrations.AddField(
            model_name='leaveencashmenthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveencashmenthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encashments', to='leave.LeaveAccount'),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveencashment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveencashment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_encashments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapproval',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveapproval_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapproval',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapproval',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveapproval_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapproval',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_approval', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='leaveaccounthistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leave.LeaveAccount'),
        ),
        migrations.AddField(
            model_name='leaveaccounthistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_accounts_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveaccounthistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveaccounthistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveaccounthistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveaccounthistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveaccounthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_account_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveaccount',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveaccount_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveaccount',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_leaveaccount_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveaccount',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='leaveaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hourlyleaveperday',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_hourlyleaveperday_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hourlyleaveperday',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_hourlyleaveperday_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hourlyleaveperday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_leaves_per_day', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deductionrule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_deductionrule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deductionrule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_deductionrule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deductionrule',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_rule', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='credithourrule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_credithourrule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_credithourrule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='credithourrule',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_hour_rule', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='compensatoryleaveaccount',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_compensatoryleaveaccount_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensatoryleaveaccount',
            name='leave_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_leave', to='leave.LeaveAccount'),
        ),
        migrations.AddField(
            model_name='compensatoryleaveaccount',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_compensatoryleaveaccount_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensatoryleaveaccount',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_leave', to='attendance.TimeSheet'),
        ),
        migrations.AddField(
            model_name='compensatoryleave',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_compensatoryleave_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensatoryleave',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_compensatoryleave_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compensatoryleave',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensatory_rule', to='leave.LeaveRule'),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_accumulationrule_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_accumulationrule_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='rule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accumulation_rule', to='leave.LeaveRule'),
        ),
        migrations.AlterUniqueTogether(
            name='mastersetting',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('name', 'master_setting')},
        ),
        migrations.AlterUniqueTogether(
            name='leaveapproval',
            unique_together={('organization', 'authority_order'), ('organization', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='hourlyleaveperday',
            unique_together={('user', 'leave_for', 'is_paid')},
        ),
    ]
