# Generated by Django 2.2.11 on 2021-04-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverule',
            name='proportionate_on_contract_end_date',
            field=models.NullBooleanField(help_text='Proportionate leave on contract_end_date.'),
        ),
    ]
