# Generated by Django 2.2.11 on 2021-04-13 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveencashmenthistory',
            name='status',
        ),
        migrations.AddField(
            model_name='leaveencashment',
            name='approved_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='leaveencashmenthistory',
            name='action',
            field=models.CharField(default='Generated', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaveencashmenthistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acted_leave_encashment_histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveencashmenthistory',
            name='new_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='leaveencashmenthistory',
            name='previous_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='leaveencashmenthistory',
            name='remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Approved', 'Approved'), ('Encashed', 'Encashed'), ('Denied', 'Denied')], max_length=15),
        ),
    ]
