# Generated by Django 2.2.11 on 2021-05-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverule_proportionate_on_contract_end_date'),
        ('leave', '0003_auto_20210413_1029'),
    ]

    operations = [
    ]
