# Generated by Django 2.2.11 on 2021-04-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20210413_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulationrule',
            name='count_if_present_in_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='count_if_present_in_off_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='exclude_absent_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='exclude_half_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='exclude_holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='exclude_off_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='exclude_paid_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accumulationrule',
            name='exclude_unpaid_leave',
            field=models.BooleanField(default=False),
        ),
    ]
