# Generated by Django 2.2.11 on 2021-04-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20210413_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveencashment',
            name='source',
            field=models.CharField(choices=[('Leave Renew', 'Leave Renew'), ('Employee Separation', 'Employee Separation')], default='Leave Renew', max_length=20),
        ),
    ]
