# Generated by Django 2.2.11 on 2021-05-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20210422_1656'),
        ('leave', '0004_merge_20210505_1632'),
    ]

    operations = [
    ]
