# Generated by Django 2.2.11 on 2021-05-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_merge_20210507_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverule',
            name='adjacent_offday_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverule',
            name='adjacent_offday_inclusive_leave_types',
            field=models.ManyToManyField(to='leave.LeaveType'),
        ),
        migrations.AddField(
            model_name='leaverule',
            name='adjacent_offday_inclusive_type',
            field=models.CharField(blank=True, choices=[('Exclude Holiday And Off Day', 'Exclude Holiday And Off Day'), ('Include Holiday', 'Include Holiday'), ('Include Off Day', 'Include Off Day'), ('Include Holiday And Off Day', 'Include Holiday And Off Day')], max_length=32),
        ),
    ]
