# Generated by Django 2.2.11 on 2021-05-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaveencashment_source'),
        ('leave', '0005_merge_20210507_1824'),
    ]

    operations = [
    ]
