# Generated by Django 2.2.11 on 2021-05-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20210511_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverule',
            name='adjacent_offday_inclusive_type',
            field=models.CharField(blank=True, choices=[('Include Holiday', 'Include Holiday'), ('Include Off Day', 'Include Off Day'), ('Include Holiday And Off Day', 'Include Holiday And Off Day')], max_length=32),
        ),
    ]
