# Generated by Django 2.2.11 on 2021-05-14 13:30

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0007_auto_20210514_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverule',
            name='adjacent_offday_inclusive_leave_types',
        ),
        migrations.CreateModel(
            name='AdjacentLeaveReductionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order_field', models.PositiveSmallIntegerField(default=1)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_adjacentleavereductiontypes_created', to=settings.AUTH_USER_MODEL)),
                ('leave_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduction_leave_types', to='leave.LeaveRule')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leave.LeaveType')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_adjacentleavereductiontypes_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order_field',),
            },
        ),
    ]
