# Generated by Django 2.2.11 on 2021-05-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20210514_1915'),
        ('leave', '0006_merge_20210510_1812'),
    ]

    operations = [
    ]
