# Generated by Django 2.2.11 on 2021-05-25 07:59

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0009_merge_20210518_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacentTimeSheetOffdayHolidayPenalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('penalty_for', models.DateField()),
                ('penalty', models.FloatField(default=1.0)),
                ('processed', models.NullBooleanField()),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_adjacenttimesheetoffdayholidaypenalty_created', to=settings.AUTH_USER_MODEL)),
                ('leave_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leave.LeaveAccount')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_adjacenttimesheetoffdayholidaypenalty_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
