# Generated by Django 2.2.11 on 2021-06-28 07:56

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_merge_20210518_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compensatoryleaveaccount',
            name='balance_consumed',
            field=models.FloatField(default=0, validators=[irhrs.core.validators.validate_multiple_of_half]),
        ),
        migrations.AlterField(
            model_name='compensatoryleaveaccount',
            name='balance_granted',
            field=models.FloatField(validators=[irhrs.core.validators.validate_multiple_of_half]),
        ),
    ]
