# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20210628_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accumulationrule',
            name='duration_type',
            field=models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='compensatoryleave',
            name='collapse_after_unit',
            field=models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], db_index=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='deductionrule',
            name='duration_type',
            field=models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='leaveaccounthistory',
            name='action',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Removed', 'Removed'), ('Renewed', 'Renewed'), ('Added', 'Added'), ('Deducted', 'Deducted'), ('Updated', 'Updated'), ('Initialized', 'Assigned with balance')], db_index=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='source',
            field=models.CharField(choices=[('Leave Renew', 'Leave Renew'), ('Employee Separation', 'Employee Separation')], db_index=True, default='Leave Renew', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveencashment',
            name='status',
            field=models.CharField(choices=[('Generated', 'Generated'), ('Approved', 'Approved'), ('Encashed', 'Encashed'), ('Denied', 'Denied')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='leaveencashmenthistory',
            name='action',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='part_of_day',
            field=models.CharField(blank=True, choices=[('first', 'First Half'), ('second', 'Second Half'), ('full', 'Full Day')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='recipient_type',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('approver', 'Approver')], db_index=True, default='supervisor', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Forwarded', 'Forwarded')], db_index=True, default='Requested', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequestdeletehistory',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Forwarded', 'Forwarded'), ('Denied', 'Denied')], db_index=True, default='Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequestdeletestatushistory',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Forwarded', 'Forwarded'), ('Denied', 'Denied')], db_index=True, default='Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequesthistory',
            name='action',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Forwarded', 'Forwarded')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequesthistory',
            name='recipient_type',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('approver', 'Approver')], db_index=True, default='supervisor', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='adjacent_offday_inclusive_type',
            field=models.CharField(blank=True, choices=[('Include Holiday', 'Include Holiday'), ('Include Off Day', 'Include Off Day'), ('Include Holiday And Off Day', 'Include Holiday And Off Day')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='inclusive_leave',
            field=models.CharField(choices=[('Exclude Holiday And Off Day', 'Exclude Holiday And Off Day'), ('Include Holiday', 'Include Holiday'), ('Include Off Day', 'Include Off Day'), ('Include Holiday And Off Day', 'Include Holiday And Off Day')], db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='limit_leave_duration_type',
            field=models.CharField(choices=[('Years', 'Years'), ('Months', 'Months')], db_index=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='required_experience_duration',
            field=models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], db_index=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='applicable_for_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('All', 'All')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='applicable_for_marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('All', 'All')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Years of Service', 'Years of Service'), ('Time Off', 'Time Off'), ('Compensatory', 'Compensatory'), ('Credit Hour', 'Credit Hour')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='renewalrule',
            name='duration_type',
            field=models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], db_index=True, max_length=7),
        ),
    ]
