# Generated by Django 2.2.11 on 2021-08-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_adjacenttimesheetoffdayholidaypenalty'),
        ('leave', '0011_auto_20210629_1553'),
    ]

    operations = [
    ]
