# Generated by Django 2.2.11 on 2021-10-22 12:10

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_merge_20210809_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveaccount',
            name='balance',
            field=models.FloatField(default=0, validators=[irhrs.core.validators.validate_multiple_of_half]),
        ),
        migrations.AlterField(
            model_name='leaveaccount',
            name='usable_balance',
            field=models.FloatField(default=0, validators=[irhrs.core.validators.validate_multiple_of_half]),
        ),
    ]
