# Generated by Django 2.2.11 on 2021-11-26 05:28

import django.core.validators
from django.db import migrations, models
import irhrs.core.utils.common


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_auto_20211022_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'odt', 'pdf', 'xls', 'xlsx', 'ods', 'ppt', 'pptx', 'txt', 'tif', 'tiff', 'jif', 'jfif', 'jp2', 'jpx', 'j2k', 'j2c', 'fpx', 'pcd', 'psd', 'rtf', 'gif', 'jpeg', 'jpg', 'png'])]),
        ),
    ]
