# Generated by Django 3.2.12 on 2022-03-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_auto_20211126_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjacenttimesheetoffdayholidaypenalty',
            name='processed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='can_apply_beyond_zero_balance',
            field=models.BooleanField(help_text='Can apply beyond zero balance', null=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='can_apply_half_shift',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='depletion_required',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='holiday_inclusive',
            field=models.BooleanField(help_text='Include Holidays/Off days ?', null=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='proportionate_on_contract_end_date',
            field=models.BooleanField(help_text='Proportionate leave on contract_end_date.', null=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='proportionate_on_joined_date',
            field=models.BooleanField(help_text='Proportionate leave on joined date.', null=True),
        ),
        migrations.AlterField(
            model_name='leaverule',
            name='require_docs',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='email_notification',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='sms_notification',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mastersetting',
            name='credit_hour',
            field=models.BooleanField(help_text='Flag to enable Credit Hour System.', null=True),
        ),
        migrations.AlterField(
            model_name='renewalrule',
            name='is_collapsible',
            field=models.BooleanField(null=True),
        ),
    ]
