# Generated by Django 2.2.11 on 2022-07-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_auto_20220603_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priorapprovalrule',
            name='prior_approval_unit',
            field=models.CharField(blank=True, choices=[('Days', 'Days'), ('Hours', 'Hours'), ('Minutes', 'Minutes')], max_length=20, null=True),
        ),
    ]
