# Generated by Django 2.2.11 on 2022-07-21 08:25

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irhrs.leave.utils.validations


def migrate_leave_collapsible_rule(apps, schema_editor):
    CompensatoryLeave = apps.get_model('leave', 'CompensatoryLeave')
    CompensatoryLeaveCollapsibleRule = apps.get_model(
        'leave', 'CompensatoryLeaveCollapsibleRule'
    )
    rules = CompensatoryLeave.objects.all()

    CompensatoryLeaveCollapsibleRule.objects.bulk_create([
        CompensatoryLeaveCollapsibleRule(
            rule = rule.rule,
            collapse_after = rule.collapse_after,
            collapse_after_unit = rule.collapse_after_unit
        ) for rule in rules
    ])
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0015_auto_20220601_0858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compensatoryleave',
            options={'ordering': ('created_at', 'modified_at')},
        ), 
        
        
        migrations.CreateModel(
            name='CompensatoryLeaveCollapsibleRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('collapse_after', models.FloatField(null=True, validators=[irhrs.leave.utils.validations.validate_rule_limits])),
                ('collapse_after_unit', models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], db_index=True, max_length=7, null=True)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_compensatoryleavecollapsiblerule_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_compensatoryleavecollapsiblerule_modified', to=settings.AUTH_USER_MODEL)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_collapsible_rule', to='leave.LeaveRule')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_leave_collapsible_rule),
        migrations.RemoveField(
            model_name='compensatoryleave',
            name='collapse_after',
        ),
        migrations.RemoveField(
            model_name='compensatoryleave',
            name='collapse_after_unit',
        ),
    ]
