# Generated by Django 3.2.12 on 2022-07-29 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_auto_20220307_1143'),
        ('leave', '0016_auto_20220718_1152'),
    ]

    operations = [
    ]
