# Generated by Django 2.2.11 on 2022-08-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_auto_20220718_1152'),
        ('leave', '0016_auto_20220721_1410'),
    ]

    operations = [
    ]
