# Generated by Django 3.2.12 on 2022-09-30 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_merge_20220823_1124'),
        ('leave', '0018_auto_20220729_1551'),
    ]

    operations = [
    ]
