# Generated by Django 3.2.12 on 2024-02-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_merge_20220930_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverule',
            name='proportionate_on_probation_end_date',
            field=models.BooleanField(help_text='Proportionate leave on probation end date.', null=True),
        ),
    ]
