# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('questionnaire', '0002_auto_20210211_1614'),
        ('recruitment', '0001_initial'),
        ('organization', '0002_auto_20210211_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_template_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_template_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='salarydeclaration',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_salarydeclaration_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarydeclaration',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_declarations', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='salarydeclaration',
            name='job_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_declarations', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='salarydeclaration',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_salarydeclaration_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_salary_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_salary_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencechecker',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_referencechecker_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencechecker',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_referencechecker_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencechecker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_checker', to='recruitment.ApplicantReference'),
        ),
        migrations.AddField(
            model_name='referencecheckanswer',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_referencecheckanswer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencecheckanswer',
            name='external_reference_checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_check_question_answers', to='recruitment.ReferenceChecker'),
        ),
        migrations.AddField(
            model_name='referencecheckanswer',
            name='internal_reference_checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_check_question_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencecheckanswer',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_referencecheckanswer_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencecheckanswer',
            name='reference_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_check_question_answers', to='recruitment.ReferenceCheck'),
        ),
        migrations.AddField(
            model_name='referencecheck',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_referencecheck_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencecheck',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_checks', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='referencecheck',
            name='email_template_external',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_check_external', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='referencecheck',
            name='job_apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_check', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='referencecheck',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_referencecheck_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencecheck',
            name='question_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_checks', to='recruitment.QuestionSet'),
        ),
        migrations.AddField(
            model_name='recruitmentquestionsection',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_recruitmentquestionsection_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentquestionsection',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_recruitmentquestionsection_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentquestionsection',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='recruitment.QuestionSet'),
        ),
        migrations.AddField(
            model_name='recruitmentquestionsection',
            name='questions',
            field=models.ManyToManyField(related_name='_recruitmentquestionsection_questions_+', through='recruitment.RecruitmentQuestions', to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='recruitmentquestions',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_recruitmentquestions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentquestions',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_recruitmentquestions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentquestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='recruitmentquestions',
            name='question_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_questions', to='recruitment.RecruitmentQuestionSection'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_questionset_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionset',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_questionset_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_question_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_question_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.Country'),
        ),
        migrations.AddField(
            model_name='province',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_province_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='province',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_province_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescreeninginterviewanswer',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_prescreeninginterviewanswer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescreeninginterviewanswer',
            name='external_interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screening_interview_question_answers', to='recruitment.External'),
        ),
        migrations.AddField(
            model_name='prescreeninginterviewanswer',
            name='internal_interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screening_interview_question_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescreeninginterviewanswer',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_prescreeninginterviewanswer_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescreeninginterviewanswer',
            name='pre_screening_interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_screening_interview_question_answers', to='recruitment.PreScreeningInterview'),
        ),
        migrations.AddField(
            model_name='prescreeninginterview',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_prescreeninginterview_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescreeninginterview',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screening_interviews', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='prescreeninginterview',
            name='email_template_external',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screening_interviews_external', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='prescreeninginterview',
            name='job_apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_screening_interview', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='prescreeninginterview',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_prescreeninginterview_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescreeninginterview',
            name='question_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_screening_interviews', to='recruitment.QuestionSet'),
        ),
        migrations.AddField(
            model_name='prescreeninginterview',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screening_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescreening',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_prescreening_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescreening',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screenings', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='prescreening',
            name='job_apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_screening', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='prescreening',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_prescreening_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescreening',
            name='question_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_screenings', to='recruitment.QuestionSet'),
        ),
        migrations.AddField(
            model_name='prescreening',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screenings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postscreening',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_postscreening_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postscreening',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_screenings', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='postscreening',
            name='job_apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_screening', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='postscreening',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_postscreening_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postscreening',
            name='question_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post_screenings', to='recruitment.QuestionSet'),
        ),
        migrations.AddField(
            model_name='postscreening',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_screenings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_noobjection_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_objection_email_templates', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_objections', to='recruitment.Job'),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='job_apply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_objections', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_noobjection_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='report_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_objection_report_templates', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='noobjection',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_objections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='recruitment.City'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='recruitment.Country'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_location_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_location_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_language_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='language',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_language_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobsetting',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setting', to='recruitment.Job'),
        ),
        migrations.AddField(
            model_name='jobquestionanswer',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobquestionanswer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobquestionanswer',
            name='job_apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='jobquestionanswer',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobquestionanswer_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobquestion',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobquestion_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobquestion',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='recruitment.Job'),
        ),
        migrations.AddField(
            model_name='jobquestion',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobquestion_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_questions', to='recruitment.QuestionSet'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobcategory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobcategory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.JobCategory'),
        ),
        migrations.AddField(
            model_name='jobbenefit',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobbenefit_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobbenefit',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobbenefit_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobattachment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobattachment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobattachment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='recruitment.Job'),
        ),
        migrations.AddField(
            model_name='jobattachment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobattachment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplystagestatus',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobapplystagestatus_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplystagestatus',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobapplystagestatus_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplystagestatus',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_status', to='recruitment.JobApplyStage'),
        ),
        migrations.AddField(
            model_name='jobapplystage',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobapplystage_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplystage',
            name='job_apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_stages', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='jobapplystage',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_jobapplystage_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='applicant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_job', to='recruitment.Applicant'),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='internal_applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='recruitment.JobBenefit'),
        ),
        migrations.AddField(
            model_name='job',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='organization.OrganizationBranch'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_job_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='organization.OrganizationDivision'),
        ),
        migrations.AddField(
            model_name='job',
            name='document_categories',
            field=models.ManyToManyField(blank=True, to='common.DocumentCategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='organization.EmploymentLevel'),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='organization.EmploymentStatus'),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Industry'),
        ),
        migrations.AddField(
            model_name='job',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_job_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='offered_salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='recruitment.Salary'),
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='job',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='organization.KnowledgeSkillAbility'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='organization.EmploymentJobTitle'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interviewanswer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='external_interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_question_answers', to='recruitment.External'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='internal_interviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_question_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_question_answers', to='recruitment.Interview'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interviewanswer_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interview_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='interview',
            name='email_template_external',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_external', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='interview',
            name='job_apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='interview',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_interview_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='question_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview_questions', to='recruitment.QuestionSet'),
        ),
        migrations.AddField(
            model_name='externaldocument',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewer_documents', to='common.DocumentCategory'),
        ),
        migrations.AddField(
            model_name='externaldocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.External'),
        ),
        migrations.AddField(
            model_name='external',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_external_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='external',
            name='ksao',
            field=models.ManyToManyField(to='organization.KnowledgeSkillAbility'),
        ),
        migrations.AddField(
            model_name='external',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_external_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='external',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer', to='users.ExternalUser'),
        ),
        migrations.AddField(
            model_name='district',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_district_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_district_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruitment.Province'),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_country_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_country_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_city_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='recruitment.District'),
        ),
        migrations.AddField(
            model_name='city',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_city_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_question_answers', to='recruitment.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_assessmentanswer_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='external_assessment_verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_question_answers', to='recruitment.External'),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='internal_assessment_verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_question_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_assessmentanswer_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_assessment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='email_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='email_template_external',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_external', to='recruitment.Template'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='job_apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='recruitment.JobApply'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_assessment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='question_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_apply_assessments', to='recruitment.QuestionSet'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_apply_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantworkexperience',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='recruitment.Applicant'),
        ),
        migrations.AddField(
            model_name='applicantreference',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='recruitment.Applicant'),
        ),
        migrations.AddField(
            model_name='applicanteducation',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='recruitment.Applicant'),
        ),
        migrations.AddField(
            model_name='applicantattachment',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='recruitment.Applicant'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_address_applicants', to='recruitment.Location'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='expected_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_salary_users', to='recruitment.Salary'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(to='organization.KnowledgeSkillAbility'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='users.ExternalUser'),
        ),
        migrations.AlterUniqueTogether(
            name='recruitmentquestions',
            unique_together={('question_section', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='jobcategory',
            unique_together={('parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'district')},
        ),
    ]
