# Generated by Django 2.2.11 on 2021-10-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expected_salary_required',
            field=models.BooleanField(default=False),
        ),
    ]
