# Generated by Django 2.2.11 on 2021-10-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_job_expected_salary_required'),
        ('recruitment', '0003_auto_20210629_1553'),
    ]

    operations = [
    ]
