# Generated by Django 2.2.11 on 2022-01-17 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_merge_20211029_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='external_assessment_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_question_answers', to='recruitment.External'),
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='internal_assessment_verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_question_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewanswer',
            name='external_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_question_answers', to='recruitment.External'),
        ),
        migrations.AlterField(
            model_name='interviewanswer',
            name='internal_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_question_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postscreening',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescreening',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescreeninginterview',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescreeninginterviewanswer',
            name='external_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screening_interview_question_answers', to='recruitment.External'),
        ),
        migrations.AlterField(
            model_name='prescreeninginterviewanswer',
            name='internal_interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_screening_interview_question_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescreeninginterviewanswer',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencecheck',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencecheckanswer',
            name='external_reference_checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_check_question_answers', to='recruitment.ReferenceChecker'),
        ),
        migrations.AlterField(
            model_name='referencecheckanswer',
            name='internal_reference_checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_check_question_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
