# Generated by Django 2.2.11 on 2022-01-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20220117_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewanswer',
            options={'verbose_name_plural': 'Interview answers'},
        ),
    ]
