# Generated by Django 2.2.11 on 2022-04-06 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20220117_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country_ref',
            field=models.ForeignKey(blank=True, default=603, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='recruitment.Country'),
        ),
    ]
