# Generated by Django 3.2.12 on 2022-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20220117_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewanswer',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='job',
            name='hiring_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='jobquestionanswer',
            name='data',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='postscreening',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescreening',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescreeninginterview',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescreeninginterviewanswer',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencecheck',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencecheckanswer',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
