# Generated by Django 2.2.11 on 2022-04-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20220117_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='conflict_of_interest',
            field=models.BooleanField(default=False),
        ),
    ]
