# Generated by Django 2.2.11 on 2022-04-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_assessmentanswer_conflict_of_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='conflict_of_interest',
            field=models.BooleanField(default=False),
        ),
    ]
