# Generated by Django 2.2.11 on 2022-04-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_location_country_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
