# Generated by Django 2.2.11 on 2022-04-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_interview_conflict_of_interest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='conflict_of_interest',
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='conflict_of_interest',
            field=models.BooleanField(default=False),
        ),
    ]
