# Generated by Django 2.2.11 on 2022-05-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_auto_20220421_1629'),
        ('recruitment', '0008_location_postal_code'),
    ]

    operations = [
    ]
