# Generated by Django 3.2.12 on 2022-05-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20220307_1154'),
        ('recruitment', '0010_merge_20220506_1303'),
    ]

    operations = [
    ]
