# Generated by Django 3.2.12 on 2022-11-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_merge_20220516_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='education_degree',
            field=models.CharField(blank=True, choices=[('PHD', 'PHD'), ('Master', 'Master'), ('Bachelor', 'Bachelor'), ('Diploma', 'Diploma'), ('Intermediate', 'Intermediate'), ('SLC', 'SLC'), ('Below SLC', 'Below SLC')], max_length=20),
        ),
    ]
