# Generated by Django 3.2.12 on 2022-11-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_merge_20220516_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='curriculum_vitae_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='references_required',
            field=models.BooleanField(default=False),
        ),
    ]
