# Generated by Django 3.2.12 on 2022-11-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_alter_applicant_education_degree'),
        ('recruitment', '0012_auto_20221109_1124'),
    ]

    operations = [
    ]
