# Generated by Django 3.2.12 on 2023-02-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_merge_20221115_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='show_vacancy_number',
            field=models.BooleanField(default=False),
        ),
    ]
