# Generated by Django 3.2.12 on 2023-03-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_job_show_vacancy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescreeninginterview',
            name='has_weightage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescreeninginterviewanswer',
            name='interviewer_weightage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
