# Generated by Django 3.2.12 on 2023-03-14 06:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_job_show_vacancy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='stages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('applied', 'Applied'), ('screened', 'Screened'), ('shortlisted', 'Shortlisted'), ('pre_screening_interviewed', 'Pre Screening Interview'), ('assessment_taken', 'Assessment Taken'), ('interviewed', 'Interviewed'), ('reference_verified', 'Reference Verified'), ('salary_declared', 'Salary Declared'), ('selected', 'Selected'), ('rejected', 'Rejected')], max_length=50), default=['applied', 'screened', 'shortlisted', 'pre_screening_interviewed', 'assessment_taken', 'interviewed', 'reference_verified', 'salary_declared', 'selected', 'rejected'], size=10),
        ),
    ]
