# Generated by Django 3.2.12 on 2023-03-14 06:40

import django.contrib.postgres.fields
from django.db import migrations, models
import irhrs.recruitment.models.job


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_job_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='stages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('applied', 'Applied'), ('screened', 'Screened'), ('shortlisted', 'Shortlisted'), ('pre_screening_interviewed', 'Pre Screening Interview'), ('assessment_taken', 'Assessment Taken'), ('interviewed', 'Interviewed'), ('reference_verified', 'Reference Verified'), ('salary_declared', 'Salary Declared'), ('selected', 'Selected'), ('rejected', 'Rejected')], max_length=50), default=irhrs.recruitment.models.job.job_stages_default, size=10),
        ),
    ]
