# Generated by Django 3.2.12 on 2023-03-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0015_auto_20230315_1646'),
        ('recruitment', '0016_alter_job_stages'),
    ]

    operations = [
    ]
