# Generated by Django 3.2.12 on 2023-02-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_bank_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('Late In Email', 'LateIn Email'), ('Absent Email', 'Absent Email'), ('Overtime Email', 'Overtime Email'), ('Leave Email', 'Leave Email'), ('Weekly Attendance Report Email', 'Weekly Attendance Report Email')], db_index=True, max_length=40),
        ),
    ]
