# Generated by Django 2.2.11 on 2021-02-11 10:29

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import irhrs.core.utils.common
import irhrs.core.validators
import irhrs.hris.models.onboarding_offboarding
import irhrs.task.utils.task_attachment_path


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('affects_experience', models.BooleanField()),
                ('affects_payroll', models.BooleanField()),
                ('affects_work_shift', models.BooleanField()),
                ('affects_core_tasks', models.BooleanField()),
                ('affects_leave_balance', models.BooleanField()),
                ('badge_visibility', models.CharField(choices=[('n', 'Hide from Directory and Employee List'), ('b', 'Show in Directory and Employee List'), ('d', 'Show in Directory Only'), ('l', 'Show in Employee List Only')], default='n', max_length=1)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('leave', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeChangeTypeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSeparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parted_date', models.DateField(help_text='The date employee asked to leave the company.', null=True)),
                ('effective_date', models.DateField(help_text='The date, HR accepted the resignation.', null=True)),
                ('release_date', models.DateField(help_text='The date, employee disappears from the system.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('letters-generated', 'Letters Generated'), ('pre-active', 'Pre Task Active'), ('pre-completed', 'Pre Task Completed'), ('post-active', 'Post Task Active'), ('post-completed', 'Post Task Completed'), ('leave-reviewed', 'Leave Reviewed'), ('attendance-reviewed', 'Attendance Reviewed'), ('tasks-reviewed', 'Pending Tasks Reviewed'), ('payroll-reviewed', 'Payroll Reviewed'), ('exit-interview-created', 'Exit Interview Created'), ('exit-interview-reviewed', 'Exit Interview Reviewed')], default='active', max_length=23)),
                ('remarks', models.CharField(max_length=600)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
            bases=(irhrs.hris.models.onboarding_offboarding.PrePostTaskMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EmployeeSeparationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=100, validators=[irhrs.core.validators.validate_title])),
                ('category', models.CharField(choices=[('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Contract Completed', 'Contract Completed'), ('Other', 'Other')], max_length=20)),
                ('display_leave', models.BooleanField(default=True)),
                ('display_payroll', models.BooleanField(default=True)),
                ('display_attendance_details', models.BooleanField(default=True)),
                ('display_pending_tasks', models.BooleanField(default=True)),
                ('badge_visibility', models.CharField(choices=[('n', 'Hide from Directory and Employee List'), ('b', 'Show in Directory and Employee List'), ('d', 'Show in Directory Only'), ('l', 'Show in Employee List Only')], default='n', max_length=1)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('letters-generated', 'Letters Generated'), ('pre-active', 'Pre Task Active'), ('pre-completed', 'Pre Task Completed'), ('post-active', 'Post Task Active'), ('post-completed', 'Post Task Completed'), ('experience-added', 'Experience Added'), ('payroll-changed', 'Payroll Changed'), ('workshift-changed', 'Workshift Changed'), ('leave-updated', 'Leave Updated'), ('core-tasks-updated', 'Core Tasks Updated')], default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, max_length=5000)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
            bases=(irhrs.hris.models.onboarding_offboarding.PrePostTaskMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExitInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField(null=True, validators=[irhrs.core.validators.validate_future_datetime])),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExitInterviewQuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uri', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('not sent', 'Not Sent'), ('failed', 'Failed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('downloaded', 'Downloaded'), ('saved', 'SAVED')], default='not sent', max_length=10)),
                ('remarks', models.TextField(max_length=600)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedLetterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('not sent', 'Not Sent'), ('failed', 'Failed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('downloaded', 'Downloaded'), ('saved', 'SAVED')], max_length=10)),
                ('remarks', models.TextField(blank=True, max_length=600, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HRApprovalUserResignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(max_length=600)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.ImageField(help_text='Profile Image', null=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[irhrs.core.validators.validate_image_file_extension])),
                ('issued_on', models.DateField(help_text='Issued Date', null=True)),
                ('expire_on', models.DateField(help_text='Expiry Date', null=True)),
                ('full_name', models.CharField(help_text='Full name', max_length=255)),
                ('user_email', models.CharField(blank=True, help_text='User Email', max_length=255)),
                ('employee_code', models.CharField(blank=True, help_text='Employee Code', max_length=150)),
                ('division', models.CharField(blank=True, help_text='Division', max_length=150)),
                ('employment_level', models.CharField(blank=True, help_text='Employment Level', max_length=150)),
                ('phone_no', models.CharField(blank=True, help_text='Contact Number of Employee', max_length=50, null=True)),
                ('address', models.CharField(blank=True, help_text='Address of the employee', max_length=255, null=True)),
                ('citizenship_number', models.CharField(blank=True, help_text='Citizenship Number', max_length=255, null=True)),
                ('signature', models.ImageField(help_text='Signature of the employee', null=True, upload_to='')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdCardTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of template', max_length=50)),
                ('logo', models.ImageField(help_text='Organization logo', null=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[irhrs.core.validators.validate_image_file_extension])),
                ('background_image', models.ImageField(blank=True, help_text='Background Image of card.', null=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[irhrs.core.validators.validate_image_file_extension])),
                ('auth_signature', models.ImageField(blank=True, help_text='Authorized signature', null=True, upload_to=irhrs.core.utils.common.get_upload_path, validators=[irhrs.core.validators.validate_image_file_extension])),
                ('slogan', models.TextField(blank=True, help_text='Slogan of organization', max_length=1000)),
                ('org_address', models.CharField(blank=True, help_text='Address of organization.', max_length=200, null=True)),
                ('org_phone_no', models.CharField(blank=True, help_text='Phone Number Section text.', max_length=100, null=True)),
                ('org_email', models.EmailField(blank=True, help_text='Email of organization', max_length=254, null=True)),
                ('profile_image_height', models.IntegerField(blank=True, help_text='Height of profile image used with this template', null=True)),
                ('profile_image_width', models.IntegerField(blank=True, help_text='Width of profile image used with this template', null=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveChangeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField()),
                ('update_balance', models.FloatField(null=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('offer', 'Offer Letter'), ('on', 'On Boarding'), ('off', 'Off Boarding'), ('change', 'Change Type')], max_length=10)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreEmployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, validators=[irhrs.core.utils.common.validate_full_name])),
                ('address', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('deadline', models.DateTimeField(validators=[irhrs.core.validators.validate_future_datetime])),
                ('date_of_join', models.DateField(validators=[irhrs.core.validators.validate_future_date])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=20)),
                ('job_description', models.TextField(blank=True, max_length=100000)),
                ('job_specification', models.TextField(blank=True, max_length=100000)),
                ('contract_period', models.DateField(null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('letters-generated', 'Letters Generated'), ('pre-active', 'Pre Task Active'), ('pre-completed', 'Pre Task Completed'), ('post-active', 'Post Task Active'), ('post-completed', 'Post Task Completed'), ('employee-added', 'Employee Added'), ('supervisor-added', 'Supervisor Added')], default='active', max_length=20)),
                ('step', models.PositiveSmallIntegerField(help_text='Step/Grade of the employee to join.', null=True, validators=[irhrs.core.validators.MinMaxValueValidator(max_value=100, min_value=0)])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            bases=(irhrs.hris.models.onboarding_offboarding.PrePostTaskMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ResignationApprovalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approve_by', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], default='Supervisor', max_length=10)),
                ('supervisor_level', models.CharField(blank=True, choices=[('First', '1st Level'), ('Second', '2nd Level'), ('Third', '3rd Level')], max_length=6, null=True)),
                ('approval_level', models.IntegerField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, max_length=600, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskFromTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('priority', models.CharField(choices=[('MINOR', 'MINOR'), ('MAJOR', 'MAJOR'), ('CRITICAL', 'CRITICAL')], default='MINOR', max_length=9)),
                ('deadline', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('changeable_deadline', models.BooleanField(default=False, help_text='Responsible Can Change Deadline', null=True)),
                ('include_employee', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskFromTemplateAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(upload_to=irhrs.task.utils.task_attachment_path.get_task_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'odt', 'pdf', 'xls', 'xlsx', 'ods', 'ppt', 'pptx', 'txt', 'tif', 'tiff', 'jif', 'jfif', 'jp2', 'jpx', 'j2k', 'j2c', 'fpx', 'pcd', 'psd', 'rtf', 'gif', 'jpeg', 'jpg', 'png'])])),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskFromTemplateChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TaskFromTemplateResponsiblePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskTemplateTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, validators=[irhrs.core.validators.validate_title])),
                ('template_type', models.CharField(choices=[('on', 'On Boarding'), ('off', 'Off Boarding'), ('change', 'Change Type')], max_length=6)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserResignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateField(validators=[irhrs.core.validators.validate_future_date])),
                ('reason', models.TextField(max_length=600)),
                ('remarks', models.TextField(max_length=600)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], default='Requested', max_length=25)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserResignationApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], max_length=25)),
                ('role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], max_length=25)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('remarks', models.TextField(max_length=600)),
            ],
            options={
                'ordering': ('level',),
            },
        ),
        migrations.CreateModel(
            name='UserResignationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=20)),
                ('target', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True, max_length=600)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
