# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payroll', '0001_initial'),
        ('hris', '0001_initial'),
        ('leave', '0001_initial'),
        ('users', '0001_initial'),
        ('task', '0001_initial'),
        ('questionnaire', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_auto_20210211_1614'),
        ('common', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresignationhistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresignationhistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='hris.UserResignation'),
        ),
        migrations.AddField(
            model_name='userresignationapproval',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_userresignationapproval_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresignationapproval',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_userresignationapproval_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresignationapproval',
            name='resignation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='hris.UserResignation'),
        ),
        migrations.AddField(
            model_name='userresignationapproval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresignation',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_userresignation_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresignation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresignation',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_userresignation_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userresignation',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resignation_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_tasktracking_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='employment_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='hris.EmploymentReview'),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_tasktracking_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='pre_employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='hris.PreEmployment'),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='separation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='hris.EmployeeSeparation'),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='task_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_tasks', to='hris.TaskTemplateTitle'),
        ),
        migrations.AddField(
            model_name='tasktracking',
            name='tasks',
            field=models.ManyToManyField(to='hris.TaskTemplateMapping'),
        ),
        migrations.AddField(
            model_name='tasktemplatetitle',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_tasktemplatetitle_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplatetitle',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_tasktemplatetitle_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplatetitle',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='tasktemplatemapping',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_tasktemplatemapping_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplatemapping',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_tasktemplatemapping_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplatemapping',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
        migrations.AddField(
            model_name='tasktemplatemapping',
            name='template_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hris.TaskFromTemplate'),
        ),
        migrations.AddField(
            model_name='taskfromtemplateresponsibleperson',
            name='core_tasks',
            field=models.ManyToManyField(to='task.CoreTask'),
        ),
        migrations.AddField(
            model_name='taskfromtemplateresponsibleperson',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_taskfromtemplateresponsibleperson_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplateresponsibleperson',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_taskfromtemplateresponsibleperson_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplateresponsibleperson',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_persons', to='hris.TaskFromTemplate'),
        ),
        migrations.AddField(
            model_name='taskfromtemplateresponsibleperson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplatechecklist',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_taskfromtemplatechecklist_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplatechecklist',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_taskfromtemplatechecklist_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplatechecklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='hris.TaskFromTemplate'),
        ),
        migrations.AddField(
            model_name='taskfromtemplateattachment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_taskfromtemplateattachment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplateattachment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_taskfromtemplateattachment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplateattachment',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='hris.TaskFromTemplate'),
        ),
        migrations.AddField(
            model_name='taskfromtemplate',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_taskfromtemplate_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplate',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_taskfromtemplate_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplate',
            name='observers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskfromtemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='hris.TaskTemplateTitle'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_statushistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='employment_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hris.EmploymentReview'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_statushistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='pre_employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hris.PreEmployment'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='separation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hris.EmployeeSeparation'),
        ),
        migrations.AddField(
            model_name='resignationapprovalsetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_resignationapprovalsetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resignationapprovalsetting',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resignation_setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resignationapprovalsetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_resignationapprovalsetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resignationapprovalsetting',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_setting', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationBranch'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_preemployment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.OrganizationDivision'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='employment_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.EmploymentLevel'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='employment_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.EmploymentStatus'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='generated_letter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hris.GeneratedLetter'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.EmploymentJobTitle'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_preemployment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='payroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.Package'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='post_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tasks_employments', to='hris.TaskTemplateTitle'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='pre_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_task_employments', to='hris.TaskTemplateTitle'),
        ),
        migrations.AddField(
            model_name='preemployment',
            name='template_letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_employments', to='hris.LetterTemplate'),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_lettertemplate_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_lettertemplate_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lettertemplate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='leavechangetype',
            name='change_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_changes', to='hris.EmployeeChangeTypeDetail'),
        ),
        migrations.AddField(
            model_name='leavechangetype',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_leavechangetype_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavechangetype',
            name='leave_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.LeaveAccount'),
        ),
        migrations.AddField(
            model_name='leavechangetype',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.LeaveType'),
        ),
        migrations.AddField(
            model_name='leavechangetype',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_leavechangetype_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_idcardtemplate_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_idcardtemplate_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='organization',
            field=models.ForeignKey(help_text='Organization associated with template', on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='sample',
            field=models.ForeignKey(help_text='Template sample from commons', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='common.IdCardSample'),
        ),
        migrations.AddField(
            model_name='idcard',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_idcard_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idcard',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_idcard_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idcard',
            name='template',
            field=models.ForeignKey(help_text='Id Card Template', on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='hris.IdCardTemplate'),
        ),
        migrations.AddField(
            model_name='idcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrapprovaluserresignation',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_hrapprovaluserresignation_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrapprovaluserresignation',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_hrapprovaluserresignation_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrapprovaluserresignation',
            name='resignation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_approval', to='hris.UserResignation'),
        ),
        migrations.AddField(
            model_name='hrapprovaluserresignation',
            name='separation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hris.EmployeeSeparationType'),
        ),
        migrations.AddField(
            model_name='generatedletterhistory',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_generatedletterhistory_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedletterhistory',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hris.GeneratedLetter'),
        ),
        migrations.AddField(
            model_name='generatedletterhistory',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_generatedletterhistory_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_generatedletter_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='employment_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_letters', to='hris.EmploymentReview'),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='letter_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_letters', to='hris.LetterTemplate'),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_generatedletter_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='pre_employment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_letters', to='hris.PreEmployment'),
        ),
        migrations.AddField(
            model_name='generatedletter',
            name='separation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_letters', to='hris.EmployeeSeparation'),
        ),
        migrations.AddField(
            model_name='exitinterviewquestionset',
            name='questions',
            field=models.ManyToManyField(to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_exitinterview_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_response', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_exitinterview_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_interviews', to='hris.ExitInterviewQuestionSet'),
        ),
        migrations.AddField(
            model_name='exitinterview',
            name='separation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_interview', to='hris.EmployeeSeparation'),
        ),
        migrations.AddField(
            model_name='employmentreview',
            name='change_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_reviews', to='hris.ChangeType'),
        ),
        migrations.AddField(
            model_name='employmentreview',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_employmentreview_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentreview',
            name='detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hris.EmployeeChangeTypeDetail'),
        ),
        migrations.AddField(
            model_name='employmentreview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentreview',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_employmentreview_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentreview',
            name='post_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_task_reviews', to='hris.TaskTemplateTitle'),
        ),
        migrations.AddField(
            model_name='employmentreview',
            name='pre_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_task_reviews', to='hris.TaskTemplateTitle'),
        ),
        migrations.AddField(
            model_name='employeeseparationtype',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_employeeseparationtype_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeseparationtype',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_employeeseparationtype_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeseparationtype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_types', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='employeeseparation',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_employeeseparation_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeseparation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeseparation',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_employeeseparation_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeseparation',
            name='post_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='separation_post_tasks', to='hris.TaskTemplateTitle'),
        ),
        migrations.AddField(
            model_name='employeeseparation',
            name='pre_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='separation_pre_tasks', to='hris.TaskTemplateTitle'),
        ),
        migrations.AddField(
            model_name='employeeseparation',
            name='separation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hris.EmployeeSeparationType'),
        ),
        migrations.AddField(
            model_name='employeechangetypedetail',
            name='change_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='hris.ChangeType'),
        ),
        migrations.AddField(
            model_name='employeechangetypedetail',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_employeechangetypedetail_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeechangetypedetail',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_employeechangetypedetail_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeechangetypedetail',
            name='new_experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_change_types', to='users.UserExperience'),
        ),
        migrations.AddField(
            model_name='employeechangetypedetail',
            name='new_payroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_change_types', to='payroll.Package'),
        ),
        migrations.AddField(
            model_name='employeechangetypedetail',
            name='new_work_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_change_types', to='attendance.WorkShift'),
        ),
        migrations.AddField(
            model_name='employeechangetypedetail',
            name='old_experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_change_types', to='users.UserExperience'),
        ),
        migrations.AddField(
            model_name='employeechangetypedetail',
            name='old_payroll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_change_types', to='payroll.Package'),
        ),
        migrations.AddField(
            model_name='employeechangetypedetail',
            name='old_work_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_change_types', to='attendance.WorkShift'),
        ),
        migrations.AddField(
            model_name='emailsetting',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_emailsetting_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsetting',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_emailsetting_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailsetting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_setting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changetype',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_changetype_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changetype',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_changetype_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changetype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_change_types', to='organization.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='taskfromtemplatechecklist',
            unique_together={('task', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='resignationapprovalsetting',
            unique_together={('organization', 'approval_level'), ('organization', 'employee'), ('organization', 'supervisor_level')},
        ),
        migrations.AlterUniqueTogether(
            name='preemployment',
            unique_together={('email', 'full_name')},
        ),
    ]
