# Generated by Django 2.2.11 on 2021-04-27 13:53

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0003_auto_20210413_1029'),
        ('hris', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEncashmentOnSeparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('encashment_balance', models.FloatField()),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_leaveencashmentonseparation_created', to=settings.AUTH_USER_MODEL)),
                ('leave_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encashment_edits_on_separation', to='leave.LeaveAccount')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_leaveencashmentonseparation_modified', to=settings.AUTH_USER_MODEL)),
                ('separation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encashment_edits', to='hris.EmployeeSeparation')),
            ],
            options={
                'unique_together': {('separation', 'leave_account')},
            },
        ),
        migrations.CreateModel(
            name='LeaveEncashmentOnSeparationChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('previous_balance', models.FloatField()),
                ('new_balance', models.FloatField()),
                ('remarks', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_leaveencashmentonseparationchangehistory_created', to=settings.AUTH_USER_MODEL)),
                ('encashment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hris.LeaveEncashmentOnSeparation')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_leaveencashmentonseparationchangehistory_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
