# Generated by Django 2.2.11 on 2021-05-06 05:52

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20210211_1614'),
        ('common', '0003_dutystation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hris', '0002_auto_20210211_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyStationAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_dutystationassignment_created', to=settings.AUTH_USER_MODEL)),
                ('duty_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='common.DutyStation')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hris_dutystationassignment_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duty_station_assignments', to='organization.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_duty_stations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
