# Generated by Django 2.2.11 on 2021-05-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0003_auto_20210429_0947'),
        ('hris', '0003_leaveencashmentonseparation_leaveencashmentonseparationchangehistory'),
    ]

    operations = [
    ]
