# Generated by Django 2.2.11 on 2021-05-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0004_merge_20210510_1812'),
        ('hris', '0004_merge_20210507_1159'),
    ]

    operations = [
    ]
