# Generated by Django 2.2.11 on 2021-06-03 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20210510_1748'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hris', '0005_merge_20210510_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='type',
            field=models.CharField(choices=[('offer', 'Offer Letter'), ('custom', 'Custom'), ('on', 'On Boarding'), ('off', 'Off Boarding'), ('change', 'Change Type')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='resignationapprovalsetting',
            unique_together={('organization', 'employee')},
        ),
    ]
