# Generated by Django 2.2.11 on 2021-06-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0006_auto_20210603_1234'),
        ('hris', '0006_auto_20210525_1458'),
    ]

    operations = [
    ]
