# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0007_merge_20210629_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetype',
            name='badge_visibility',
            field=models.CharField(choices=[('n', 'Hide from Directory and Employee List'), ('b', 'Show in Directory and Employee List'), ('d', 'Show in Directory Only'), ('l', 'Show in Employee List Only')], db_index=True, default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='employeeseparation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('letters-generated', 'Letters Generated'), ('pre-active', 'Pre Task Active'), ('pre-completed', 'Pre Task Completed'), ('post-active', 'Post Task Active'), ('post-completed', 'Post Task Completed'), ('leave-reviewed', 'Leave Reviewed'), ('attendance-reviewed', 'Attendance Reviewed'), ('tasks-reviewed', 'Pending Tasks Reviewed'), ('payroll-reviewed', 'Payroll Reviewed'), ('exit-interview-created', 'Exit Interview Created'), ('exit-interview-reviewed', 'Exit Interview Reviewed')], db_index=True, default='active', max_length=23),
        ),
        migrations.AlterField(
            model_name='employeeseparationtype',
            name='badge_visibility',
            field=models.CharField(choices=[('n', 'Hide from Directory and Employee List'), ('b', 'Show in Directory and Employee List'), ('d', 'Show in Directory Only'), ('l', 'Show in Employee List Only')], db_index=True, default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='employeeseparationtype',
            name='category',
            field=models.CharField(choices=[('Resigned', 'Resigned'), ('Terminated', 'Terminated'), ('Contract Completed', 'Contract Completed'), ('Other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employmentreview',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('letters-generated', 'Letters Generated'), ('pre-active', 'Pre Task Active'), ('pre-completed', 'Pre Task Completed'), ('post-active', 'Post Task Active'), ('post-completed', 'Post Task Completed'), ('experience-added', 'Experience Added'), ('payroll-changed', 'Payroll Changed'), ('workshift-changed', 'Workshift Changed'), ('leave-updated', 'Leave Updated'), ('core-tasks-updated', 'Core Tasks Updated')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='exitinterview',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Progress', 'Progress'), ('Completed', 'Completed')], db_index=True, default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatedletter',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('not sent', 'Not Sent'), ('failed', 'Failed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('downloaded', 'Downloaded'), ('saved', 'SAVED')], db_index=True, default='not sent', max_length=10),
        ),
        migrations.AlterField(
            model_name='generatedletterhistory',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('not sent', 'Not Sent'), ('failed', 'Failed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('downloaded', 'Downloaded'), ('saved', 'SAVED')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='type',
            field=models.CharField(choices=[('offer', 'Offer Letter'), ('custom', 'Custom'), ('on', 'On Boarding'), ('off', 'Off Boarding'), ('change', 'Change Type')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='preemployment',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], db_index=True, default='Single', max_length=20),
        ),
        migrations.AlterField(
            model_name='preemployment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('letters-generated', 'Letters Generated'), ('pre-active', 'Pre Task Active'), ('pre-completed', 'Pre Task Completed'), ('post-active', 'Post Task Active'), ('post-completed', 'Post Task Completed'), ('employee-added', 'Employee Added'), ('supervisor-added', 'Supervisor Added'), ('equipments-assigned', 'Equipments Assigned')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='resignationapprovalsetting',
            name='approve_by',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], db_index=True, default='Supervisor', max_length=10),
        ),
        migrations.AlterField(
            model_name='resignationapprovalsetting',
            name='supervisor_level',
            field=models.CharField(blank=True, choices=[('First', '1st Level'), ('Second', '2nd Level'), ('Third', '3rd Level')], db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='status',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taskfromtemplate',
            name='priority',
            field=models.CharField(choices=[('MINOR', 'MINOR'), ('MAJOR', 'MAJOR'), ('CRITICAL', 'CRITICAL')], db_index=True, default='MINOR', max_length=9),
        ),
        migrations.AlterField(
            model_name='tasktemplatetitle',
            name='template_type',
            field=models.CharField(choices=[('on', 'On Boarding'), ('off', 'Off Boarding'), ('change', 'Change Type')], db_index=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='userresignation',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Canceled', 'Canceled')], db_index=True, default='Requested', max_length=25),
        ),
        migrations.AlterField(
            model_name='userresignationapproval',
            name='role',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], db_index=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='userresignationapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], db_index=True, max_length=25),
        ),
    ]
