# Generated by Django 2.2.11 on 2021-10-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0006_auto_20211027_1153'),
        ('hris', '0008_auto_20210629_1553'),
    ]

    operations = [
    ]
