# Generated by Django 2.2.11 on 2021-11-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0009_merge_20211029_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettertemplate',
            name='type',
            field=models.CharField(choices=[('offer', 'Offer Letter'), ('custom', 'Custom'), ('on', 'On Boarding'), ('off', 'Off Boarding'), ('change', 'Change Type')], db_index=True, max_length=10),
        ),
    ]
