# Generated by Django 2.2.11 on 2021-12-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0010_auto_20211125_1313'),
        ('hris', '0010_auto_20211117_1041'),
    ]

    operations = [
    ]
