# Generated by Django 3.2.12 on 2022-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0011_merge_20211223_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exitinterview',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
