# Generated by Django 3.2.12 on 2023-12-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0012_alter_exitinterview_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresignationhistory',
            name='target',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
