# Generated by Django 2.2.11 on 2021-02-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_auto_20210216_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resendpaform',
            name='reason',
            field=models.CharField(max_length=600),
        ),
    ]
