# Generated by Django 2.2.11 on 2021-02-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_auto_20210222_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subperformanceappraisalslot',
            name='status',
        ),
    ]
