# Generated by Django 2.2.11 on 2021-03-03 04:52

import cuser.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0004_remove_subperformanceappraisalslot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPerformanceAppraisalSlotWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('obtained_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_subperformanceappraisalslotweight_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_subperformanceappraisalslotweight_modified', to=settings.AUTH_USER_MODEL)),
                ('sub_performance_appraisal_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight', to='appraisal.SubPerformanceAppraisalSlot')),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
