# Generated by Django 2.2.11 on 2021-03-02 13:17

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0004_remove_subperformanceappraisalslot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='final_score',
            field=models.FloatField(default=0, validators=[irhrs.core.validators.MinMaxValueValidator(0, 100)]),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='score_deduction_factor',
            field=models.FloatField(default=0, validators=[irhrs.core.validators.MinMaxValueValidator(0, 100)]),
        ),
        migrations.AlterField(
            model_name='appraisalsetting',
            name='duration_of_involvement_type',
            field=models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], default='Months', max_length=6),
        ),
    ]
