# Generated by Django 2.2.11 on 2021-03-03 03:21

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0005_auto_20210302_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='total_score',
            field=models.PositiveIntegerField(default=0, validators=[irhrs.core.validators.MinMaxValueValidator(0, 100)]),
        ),
    ]
