# Generated by Django 2.2.11 on 2021-03-03 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0005_subperformanceappraisalslotweight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subperformanceappraisalslotweight',
            options={},
        ),
        migrations.AddField(
            model_name='subperformanceappraisalslotweight',
            name='appraiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_performance_appraisal_slot_weights', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subperformanceappraisalslotweight',
            unique_together={('appraiser', 'sub_performance_appraisal_slot')},
        ),
    ]
