# Generated by Django 2.2.11 on 2021-03-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0006_auto_20210303_1324'),
        ('appraisal', '0007_auto_20210303_1253'),
    ]

    operations = [
    ]
