# Generated by Django 2.2.11 on 2021-03-04 11:40

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0008_merge_20210304_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subperformanceappraisalslotweight',
            old_name='obtained_score',
            new_name='final_score',
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='final_score',
            field=models.FloatField(blank=True, default=None, null=True, validators=[irhrs.core.validators.MinMaxValueValidator(0, 100)]),
        ),
    ]
