# Generated by Django 2.2.11 on 2021-03-05 11:52

from django.db import migrations, models
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0009_auto_20210304_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='final_score',
            field=models.FloatField(default=0, validators=[irhrs.core.validators.MinMaxValueValidator(0, 100)]),
        ),
    ]
