# Generated by Django 2.2.11 on 2021-03-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0010_auto_20210305_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subperformanceappraisalslotweight',
            old_name='final_score',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='subperformanceappraisalslotweight',
            name='total_score',
        ),
    ]
