# Generated by Django 2.2.11 on 2021-06-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0011_auto_20210308_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsetusertype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='questionsetusertype',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
