# Generated by Django 2.2.11 on 2021-07-01 08:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0012_auto_20210625_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='appraisal_type',
            field=models.CharField(choices=[('Self Appraisal', 'Self Appraisal'), ('Subordinate Appraisal', 'Subordinate Appraisal'), ('Peer To Peer Feedback', 'Peer To Peer Feedback'), ('Supervisor Appraisal', 'Supervisor Appraisal')], db_index=True, default='Self Appraisal', max_length=25),
        ),
        migrations.AlterField(
            model_name='appraisalsetting',
            name='duration_of_involvement_type',
            field=models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], db_index=True, default='Months', max_length=6),
        ),
        migrations.AlterField(
            model_name='deadlineexceedscoredeductioncondition',
            name='deduction_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Score', 'Score')], db_index=True, default='Percentage', max_length=10),
        ),
        migrations.AlterField(
            model_name='exceptionalappraiseefiltersetting',
            name='appraisal_type',
            field=models.CharField(choices=[('Self Appraisal', 'Self Appraisal'), ('Subordinate Appraisal', 'Subordinate Appraisal'), ('Peer To Peer Feedback', 'Peer To Peer Feedback'), ('Supervisor Appraisal', 'Supervisor Appraisal')], db_index=True, default='Self Appraisal', max_length=24),
        ),
        migrations.AlterField(
            model_name='formreviewsetting',
            name='viewable_appraisal_submitted_form_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Self Appraisal', 'Self Appraisal'), ('Subordinate Appraisal', 'Subordinate Appraisal'), ('Peer To Peer Feedback', 'Peer To Peer Feedback'), ('Supervisor Appraisal', 'Supervisor Appraisal')], db_index=True, default='Self Appraisal', max_length=25), size=4),
        ),
        migrations.AlterField(
            model_name='performanceappraisalanswertype',
            name='answer_type',
            field=models.CharField(choices=[('multiple-mcq', 'Checkbox'), ('single-mcq', 'Radio Button'), ('linear-scale', 'Linear Scale'), ('short-text', 'Short Answer'), ('long-text', 'Long Answer'), ('rating-scale', 'Rating Scale')], db_index=True, default='long-text', max_length=20),
        ),
        migrations.AlterField(
            model_name='performanceappraisalanswertype',
            name='question_type',
            field=models.CharField(choices=[('ksa', 'KSA'), ('kra', 'KRA')], db_index=True, default='kra', max_length=3),
        ),
        migrations.AlterField(
            model_name='performanceappraisalformdesign',
            name='appraisal_type',
            field=models.CharField(choices=[('Self Appraisal', 'Self Appraisal'), ('Subordinate Appraisal', 'Subordinate Appraisal'), ('Peer To Peer Feedback', 'Peer To Peer Feedback'), ('Supervisor Appraisal', 'Supervisor Appraisal')], db_index=True, default='Self Appraisal', max_length=32),
        ),
        migrations.AlterField(
            model_name='subperformanceappraisalslot',
            name='question_set_status',
            field=models.CharField(choices=[('not_generated', 'Not Generated'), ('generated', 'Generated'), ('sent', 'Sent'), ('regenerated', 'Regenerated')], db_index=True, default='not_generated', max_length=14),
        ),
        migrations.AlterField(
            model_name='subperformanceappraisalslotmode',
            name='appraisal_type',
            field=models.CharField(choices=[('Self Appraisal', 'Self Appraisal'), ('Subordinate Appraisal', 'Subordinate Appraisal'), ('Peer To Peer Feedback', 'Peer To Peer Feedback'), ('Supervisor Appraisal', 'Supervisor Appraisal')], db_index=True, default='Self Appraisal', max_length=125),
        ),
    ]
