# Generated by Django 2.2.11 on 2021-08-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0013_auto_20210701_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
