# Generated by Django 2.2.11 on 2021-08-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0015_auto_20210725_1444'),
        ('appraisal', '0014_appraisal_is_draft'),
    ]

    operations = [
    ]
