# Generated by Django 2.2.11 on 2021-09-10 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import irhrs.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20210728_1836'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0016_merge_20210812_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAppraisalQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_performanceappraisalquestion_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_performanceappraisalquestion_modified', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_questions', to='questionnaire.Question')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='questionsetusertype',
            options={'ordering': ('-created_at', '-modified_at')},
        ),
        migrations.RemoveField(
            model_name='performanceappraisalquestionset',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questionsetusertype',
            name='order',
        ),
        migrations.AlterField(
            model_name='questionsetusertype',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_user_type', to='appraisal.PerformanceAppraisalQuestion'),
        ),
        migrations.CreateModel(
            name='PerformanceAppraisalQuestionSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=600, validators=[irhrs.core.validators.validate_description])),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_performanceappraisalquestionsection_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_performanceappraisalquestionsection_modified', to=settings.AUTH_USER_MODEL)),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='appraisal.PerformanceAppraisalQuestionSet')),
                ('questions', models.ManyToManyField(related_name='_performanceappraisalquestionsection_questions_+', through='appraisal.PerformanceAppraisalQuestion', to='questionnaire.Question')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='performanceappraisalquestion',
            name='question_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_questions', to='appraisal.PerformanceAppraisalQuestionSection'),
        ),
        migrations.AlterUniqueTogether(
            name='performanceappraisalquestion',
            unique_together={('question_section', 'question')},
        ),
    ]
