# Generated by Django 2.2.11 on 2021-11-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0017_auto_20211018_1205'),
        ('appraisal', '0017_auto_20210910_1614'),
    ]

    operations = [
    ]
