# Generated by Django 2.2.11 on 2022-01-31 05:12

import cuser.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0018_merge_20211110_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPerformanceAppraisalYearWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_performance_appraisal_year_weights', to=settings.AUTH_USER_MODEL)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_subperformanceappraisalyearweight_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_subperformanceappraisalyearweight_modified', to=settings.AUTH_USER_MODEL)),
                ('performance_appraisal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_performance_appraisal_year_weights', to='appraisal.PerformanceAppraisalYear')),
            ],
            options={
                'unique_together': {('appraiser', 'performance_appraisal_year')},
            },
        ),
    ]
