# Generated by Django 3.2.12 on 2022-03-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0020_alter_performanceappraisalanswertype_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='question_set',
            field=models.JSONField(null=True),
        ),
    ]
