# Generated by Django 3.2.12 on 2023-04-19 04:58

import cuser.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0031_alter_organizationethics_unique_together'),
        ('appraisal', '0021_alter_appraisal_question_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged'), ('Archived', 'Archived')], default='Pending', max_length=15)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_individualkpi_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_kpis', to='organization.fiscalyear')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_individualkpi_modified', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('success_criteria', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_kpi_created', to=settings.AUTH_USER_MODEL)),
                ('division', models.ManyToManyField(related_name='kpi_collections', to='organization.OrganizationDivision')),
                ('employment_level', models.ManyToManyField(related_name='kpi_collections', to='organization.EmploymentLevel')),
                ('job_title', models.ManyToManyField(related_name='kpi_collections', to='organization.EmploymentJobTitle')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_kpi_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_collections', to='organization.organization')),
            ],
            options={
                'unique_together': {('organization', 'title')},
            },
        ),
        migrations.CreateModel(
            name='IndividualKPIHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged'), ('Archived', 'Archived')], default='Pending', max_length=15)),
                ('remarks', models.TextField(blank=True, max_length=600, null=True)),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_individualkpihistory_created', to=settings.AUTH_USER_MODEL)),
                ('individual_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='appraisal.individualkpi')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_individualkpihistory_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtendedIndividualKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('success_criteria', models.TextField()),
                ('weightage', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_extendedindividualkpi_created', to=settings.AUTH_USER_MODEL)),
                ('individual_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_individual_kpis', to='appraisal.individualkpi')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extended_individual_kpis', to='appraisal.kpi')),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_extendedindividualkpi_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
