# Generated by Django 3.2.12 on 2023-05-04 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0022_extendedindividualkpi_individualkpi_individualkpihistory_kpi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individualkpi',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ('-created_at',)},
        ),
    ]
