# Generated by Django 3.2.12 on 2023-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0023_auto_20230504_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualkpi',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Archived', 'Archived'), ('Submitted', 'Submitted'), ('Confirmed', 'Confirmed')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='individualkpihistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Archived', 'Archived'), ('Submitted', 'Submitted'), ('Confirmed', 'Confirmed')], default='Pending', max_length=15),
        ),
    ]
