# Generated by Django 3.2.12 on 2023-06-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_alter_emailnotificationsetting_email_type'),
        ('appraisal', '0024_auto_20230612_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='division',
            field=models.ManyToManyField(blank=True, related_name='kpi_collections', to='organization.OrganizationDivision'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='employment_level',
            field=models.ManyToManyField(blank=True, related_name='kpi_collections', to='organization.EmploymentLevel'),
        ),
    ]
