# Generated by Django 3.2.12 on 2023-10-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0026_auto_20230901_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiquestionscore',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kraquestionscore',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksaoquestionscore',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
