name: Build Docker Image

on: 
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: itsbijaya/real-hr-backend
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: 54.235.14.78
            username: ubuntu
            port: 22
            key: ${{ secrets.SSHKEY }}
            script: | 
                #pull the docker image and run docker compose
                 sudo docker pull itsbijaya/real-hr-backend:latest
                 sudo docker-compose up --build        


  
        