# Generated by Django 2.2.11 on 2021-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRSPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Permission Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('organization_specific', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('User', 'User'), ('Organization', 'Organization'), ('HRIS', 'HRIS'), ('Noticeboard', 'Noticeboard'), ('Admin', 'Admin'), ('Attendance', 'Attendance'), ('Leave', 'Leave'), ('Task', 'Task'), ('Builder', 'Builder'), ('Payroll', 'Payroll'), ('Assessment', 'Assessment'), ('Training', 'Training'), ('Questionnaire', 'Questionnaire'), ('Recruitment', 'Recruitment'), ('Reimbursement', 'Reimbursement'), ('Event', 'Event')], max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-modified_at'),
                'abstract': False,
            },
        ),
    ]
