# Generated by Django 2.2.11 on 2021-02-11 10:29

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('permission', '0001_initial'),
        ('organization', '0002_auto_20210211_1614'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationgroup',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_organizationgroup_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_permission_groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_organizationgroup_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_permission_groups', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='organizationgroup',
            name='permissions',
            field=models.ManyToManyField(to='permission.HRSPermission'),
        ),
    ]
