# Generated by Django 2.2.11 on 2021-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_auto_20210215_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrspermission',
            name='category',
            field=models.CharField(choices=[('User', 'User'), ('Organization', 'Organization'), ('HRIS', 'HRIS'), ('Noticeboard', 'Noticeboard'), ('Admin', 'Admin'), ('Attendance', 'Attendance'), ('Leave', 'Leave'), ('Task', 'Task'), ('Builder', 'Builder'), ('Payroll', 'Payroll'), ('Assessment', 'Assessment'), ('Training', 'Training'), ('Questionnaire', 'Questionnaire'), ('Recruitment', 'Recruitment'), ('Reimbursement', 'Reimbursement'), ('Event', 'Event'), ('Appraisal', 'Performance Appraisal')], db_index=True, max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='hrspermission',
            name='code',
            field=models.CharField(db_index=True, max_length=5, unique=True, verbose_name='Permission Code'),
        ),
    ]
