# Generated by Django 2.2.11 on 2021-07-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_auto_20210629_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrspermission',
            name='category',
            field=models.CharField(choices=[('User', 'User'), ('Organization', 'Organization'), ('HRIS', 'HRIS'), ('Noticeboard', 'Noticeboard'), ('Admin', 'Admin'), ('Attendance', 'Attendance'), ('Leave', 'Leave'), ('Task', 'Task'), ('Builder', 'Builder'), ('Payroll', 'Payroll'), ('Assessment', 'Assessment'), ('Training', 'Training'), ('Questionnaire', 'Questionnaire'), ('Recruitment', 'Recruitment'), ('Reimbursement', 'Reimbursement'), ('Event', 'Event'), ('Appraisal', 'Performance Appraisal'), ('Form', 'Form')], db_index=True, max_length=50, verbose_name='Category'),
        ),
    ]
